import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import type { ComponentProps, ReactNode } from 'react';
import { Alert, Image, Modal, Pressable, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

import { colors } from '@/constants/theme';
import { imageSource } from '@/services/media';

type IconName=ComponentProps<typeof MaterialCommunityIcons>['name'];

export function Card({children,style}:{children:ReactNode;style?:any}){return <View style={[s.card,style]}>{children}</View>}
export function Row({children,style}:{children:ReactNode;style?:any}){return <View style={[s.row,style]}>{children}</View>}
export function Divider(){return <View style={s.divider}/>}
export function Muted({children}:{children:ReactNode}){return <Text style={s.muted}>{children}</Text>}
export function SectionTitle({children,right}:{children:ReactNode;right?:ReactNode}){return <View style={s.sectionTitle}><Text style={s.sectionTitleText}>{children}</Text>{right}</View>}

export function AppButton({title,onPress,icon='check',variant='primary',disabled=false,compact=false}:{title:string;onPress:()=>void;icon?:IconName;variant?:'primary'|'secondary'|'danger'|'ghost'|'success';disabled?:boolean;compact?:boolean}){const bg=variant==='primary'?colors.primary:variant==='danger'?colors.danger:variant==='success'?colors.success:variant==='secondary'?colors.surfaceSoft:'transparent';const fg=['secondary','ghost'].includes(variant)?colors.primary:colors.white;return <TouchableOpacity disabled={disabled} onPress={onPress} style={[s.button,{backgroundColor:bg},compact&&s.buttonCompact,disabled&&{opacity:.45}]}><MaterialCommunityIcons name={icon} size={compact?16:18} color={fg}/><Text style={[s.buttonText,{color:fg}]}>{title}</Text></TouchableOpacity>}

export function IconButton({icon,onPress,label,color=colors.primary}:{icon:IconName;onPress:()=>void;label?:string;color?:string}){return <TouchableOpacity onPress={onPress} style={s.iconBtn}><MaterialCommunityIcons name={icon} color={color} size={20}/>{label?<Text style={[s.iconLabel,{color}]}>{label}</Text>:null}</TouchableOpacity>}

export function Field({label,value,onChangeText,placeholder='',keyboardType='default',multiline=false,editable=true,secureTextEntry=false}:{label:string;value:any;onChangeText:(v:string)=>void;placeholder?:string;keyboardType?:any;multiline?:boolean;editable?:boolean;secureTextEntry?:boolean}){return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput editable={editable} value={String(value??'')} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#9AA7B7" keyboardType={keyboardType} multiline={multiline} secureTextEntry={secureTextEntry} style={[s.input,multiline&&s.multiline,!editable&&{backgroundColor:'#F1F3F6'}]}/></View>}

export function ToggleRow({label,value,onChange,subtitle}:{label:string;value:boolean;onChange:(v:boolean)=>void;subtitle?:string}){return <Pressable onPress={()=>onChange(!value)} style={s.toggleRow}><View style={{flex:1}}><Text style={s.toggleLabel}>{label}</Text>{subtitle?<Muted>{subtitle}</Muted>:null}</View><View style={[s.toggle,value&&s.toggleOn]}><View style={[s.toggleKnob,value&&s.toggleKnobOn]}/></View></Pressable>}

export function Chips({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:Array<{value:string;label:string}>}){return <View style={s.chips}>{options.map(o=><Pressable key={o.value} onPress={()=>onChange(o.value)} style={[s.chip,value===o.value&&s.chipActive]}><Text style={[s.chipText,value===o.value&&s.chipTextActive]}>{o.label}</Text></Pressable>)}</View>}

export function ModuleRow({icon,title,subtitle,onPress,badge}:{icon:IconName;title:string;subtitle?:string;onPress:()=>void;badge?:string}){return <TouchableOpacity onPress={onPress} style={s.moduleRow}><View style={s.moduleIcon}><MaterialCommunityIcons name={icon} size={22} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.moduleTitle}>{title}</Text>{subtitle?<Text style={s.moduleSub}>{subtitle}</Text>:null}</View>{badge?<Text style={s.badge}>{badge}</Text>:null}<MaterialCommunityIcons name="chevron-right" size={22} color={colors.textSoft}/></TouchableOpacity>}

export function ImageThumb({path,size=72}:{path?:string;size?:number}){const src=imageSource(path);return src?<Image source={src} style={{width:size,height:size,borderRadius:12,backgroundColor:colors.surfaceSoft}} resizeMode="cover"/>:<View style={[s.imagePlaceholder,{width:size,height:size}]}><MaterialCommunityIcons name="image-outline" size={26} color={colors.textSoft}/></View>}

export function confirm(title:string,message:string,onOk:()=>void){Alert.alert(title,message,[{text:'Hủy',style:'cancel'},{text:'Đồng ý',style:'destructive',onPress:onOk}]);}

export function ChoiceModal({visible,title,options,onClose,onPick}:{visible:boolean;title:string;options:Array<{value:string;label:string;subtitle?:string}>;onClose:()=>void;onPick:(v:string)=>void}){return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}><Pressable style={s.modal} onPress={()=>{}}><Text style={s.modalTitle}>{title}</Text>{options.map(o=><TouchableOpacity key={o.value} style={s.choice} onPress={()=>{onPick(o.value);onClose();}}><Text style={s.choiceTitle}>{o.label}</Text>{o.subtitle?<Muted>{o.subtitle}</Muted>:null}</TouchableOpacity>)}<AppButton title="Đóng" variant="secondary" icon="close" onPress={onClose}/></Pressable></Pressable></Modal>}

const s=StyleSheet.create({card:{backgroundColor:colors.surface,borderRadius:16,padding:14,borderWidth:1,borderColor:colors.border,gap:10},row:{flexDirection:'row',alignItems:'center',gap:10},divider:{height:1,backgroundColor:colors.border},muted:{color:colors.textSoft,fontSize:12,lineHeight:17},sectionTitle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:4},sectionTitleText:{fontSize:17,fontWeight:'900',color:colors.text},button:{minHeight:44,borderRadius:12,paddingHorizontal:14,paddingVertical:10,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},buttonCompact:{minHeight:36,paddingVertical:7,paddingHorizontal:10},buttonText:{fontSize:13,fontWeight:'900'},iconBtn:{padding:8,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:4},iconLabel:{fontWeight:'800',fontSize:11},field:{gap:6},fieldLabel:{color:colors.text,fontSize:12,fontWeight:'800'},input:{minHeight:44,borderWidth:1,borderColor:colors.border,borderRadius:12,paddingHorizontal:12,paddingVertical:10,color:colors.text,backgroundColor:colors.surface,fontSize:14},multiline:{minHeight:90,textAlignVertical:'top'},toggleRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:5},toggleLabel:{fontWeight:'800',color:colors.text,fontSize:13},toggle:{width:44,height:26,borderRadius:20,backgroundColor:'#CDD6E0',padding:3},toggleOn:{backgroundColor:colors.primary},toggleKnob:{width:20,height:20,borderRadius:10,backgroundColor:'#fff'},toggleKnobOn:{transform:[{translateX:18}]},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingVertical:8,paddingHorizontal:11,borderWidth:1,borderColor:colors.border,borderRadius:99,backgroundColor:colors.surface},chipActive:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{color:colors.textSoft,fontWeight:'800',fontSize:11},chipTextActive:{color:'#fff'},moduleRow:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:15,padding:12,flexDirection:'row',alignItems:'center',gap:10},moduleIcon:{width:42,height:42,borderRadius:13,backgroundColor:colors.surfaceSoft,alignItems:'center',justifyContent:'center'},moduleTitle:{fontWeight:'900',color:colors.text,fontSize:14},moduleSub:{color:colors.textSoft,fontSize:11,marginTop:2},badge:{color:colors.primary,backgroundColor:colors.surfaceSoft,paddingHorizontal:7,paddingVertical:4,borderRadius:10,fontWeight:'900',fontSize:10},imagePlaceholder:{borderRadius:12,backgroundColor:colors.surfaceSoft,alignItems:'center',justifyContent:'center'},backdrop:{flex:1,backgroundColor:'rgba(10,20,30,.45)',justifyContent:'flex-end'},modal:{backgroundColor:colors.bg,borderTopLeftRadius:24,borderTopRightRadius:24,padding:18,gap:10,maxHeight:'80%'},modalTitle:{fontSize:19,fontWeight:'900',color:colors.text},choice:{padding:12,backgroundColor:colors.surface,borderRadius:12,borderWidth:1,borderColor:colors.border},choiceTitle:{fontWeight:'800',color:colors.text}});
