import { useState } from 'react';
import { Alert, Text } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen';
import { AppButton, Card, IconButton, Muted, ToggleRow } from '@/components/ui';
import { createFullBackup, restoreFullBackup } from '@/services/backup';
import { pickDocument } from '@/services/media';
import { replaceDatabaseFromSeed } from '@/db/database';
export default function Backup(){const [media,setMedia]=useState(true);return <Screen title="Sao lưu / khôi phục" subtitle="Bảo vệ dữ liệu offline" right={<IconButton icon="close" onPress={()=>router.back()}/>}><Card><Text style={{fontWeight:'900'}}>Tạo bản sao lưu toàn bộ</Text><Muted>Backup chứa dữ liệu nghiệp vụ SQLite/JSON và có thể nhúng ảnh/file dưới dạng base64.</Muted><ToggleRow label="Kèm ảnh và file" value={media} onChange={setMedia}/><AppButton title="Tạo & chia sẻ backup" icon="database-export-outline" onPress={()=>void createFullBackup(media).catch(e=>Alert.alert('Lỗi',String(e.message||e)))}/></Card><Card><Text style={{fontWeight:'900'}}>Khôi phục backup</Text><Muted>Chọn file backup QQIVA đã tạo trước đó. Dữ liệu hiện tại có thể bị thay đổi.</Muted><AppButton variant="secondary" title="Chọn file backup" icon="database-import-outline" onPress={()=>void pickDocument('BACKUP_RESTORE','',['application/json']).then(a=>a&&restoreFullBackup(a.uri)).then(()=>Alert.alert('Đã khôi phục','Hãy đóng và mở lại ứng dụng để đảm bảo mọi màn hình nạp dữ liệu mới.')).catch(e=>Alert.alert('Không thể khôi phục',String(e.message||e)))}/></Card><Card><Text style={{fontWeight:'900'}}>Khôi phục dữ liệu gốc đi kèm APK</Text><Muted>Đưa cơ sở dữ liệu về snapshot QQIVA đã đóng gói trong bản chuyển đổi này.</Muted><AppButton variant="danger" title="Reset về dữ liệu gốc" icon="backup-restore" onPress={()=>Alert.alert('Xác nhận reset','Dữ liệu đang dùng sẽ bị thay thế.',[{text:'Hủy'},{text:'Reset',style:'destructive',onPress:()=>void replaceDatabaseFromSeed().then(()=>Alert.alert('Đã reset','Khởi động lại ứng dụng.'))}])}/></Card></Screen>}
