import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen';
import { AppButton, Card, Field, IconButton, ImageThumb, Row, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';
import { getCompany, saveCompany } from '@/services/settings';
import { pickImages, takePhoto } from '@/services/media';
export default function Company(){const [d,setD]=useState<any>(null);useEffect(()=>{void getCompany().then(setD)},[]);if(!d)return <Screen title="Hồ sơ công ty"><Card><Text>Đang tải…</Text></Card></Screen>;const media=async(field:string,camera=false)=>{const a:any=camera?await takePhoto('COMPANY',field):(await pickImages({ownerType:'COMPANY',ownerId:field,multiple:false}))[0];if(a)setD({...d,[field]:a.uri})};return <Screen title="Hồ sơ công ty" subtitle="Dùng trên báo giá, hóa đơn và hợp đồng" right={<IconButton icon="close" onPress={()=>router.back()}/>}><Card><SectionTitle>Thông tin doanh nghiệp</SectionTitle><Field label="Tên công ty" value={d.name||''} onChangeText={v=>setD({...d,name:v})}/><Field label="Mô tả" multiline value={d.description||''} onChangeText={v=>setD({...d,description:v})}/><Field label="Địa chỉ" value={d.address||''} onChangeText={v=>setD({...d,address:v})}/><Row><View style={{flex:1}}><Field label="Điện thoại" value={d.phone||''} onChangeText={v=>setD({...d,phone:v})}/></View><View style={{flex:1}}><Field label="MST" value={d.tax_id||''} onChangeText={v=>setD({...d,tax_id:v})}/></View></Row><Field label="Email" value={d.email||''} onChangeText={v=>setD({...d,email:v})}/><Field label="Website" value={d.website||''} onChangeText={v=>setD({...d,website:v})}/><Field label="Người đại diện" value={d.representative||''} onChangeText={v=>setD({...d,representative:v})}/><Field label="Chức danh" value={d.representative_title||''} onChangeText={v=>setD({...d,representative_title:v})}/></Card><Card><SectionTitle>Ngân hàng</SectionTitle><Field label="Ngân hàng" value={d.bank_name||''} onChangeText={v=>setD({...d,bank_name:v})}/><Field label="Số tài khoản" value={d.bank_account||''} onChangeText={v=>setD({...d,bank_account:v})}/><Field label="Tên chủ tài khoản" value={d.bank_account_name||''} onChangeText={v=>setD({...d,bank_account_name:v})}/></Card><Media title="Logo" path={d.logo} gallery={()=>void media('logo')} camera={()=>void media('logo',true)}/><Media title="Chữ ký công ty" path={d.signature} gallery={()=>void media('signature')} camera={()=>void media('signature',true)}/><Media title="Con dấu" path={d.stamp} gallery={()=>void media('stamp')} camera={()=>void media('stamp',true)}/><Card><Field label="Tên người ký" value={d.signature_name||''} onChangeText={v=>setD({...d,signature_name:v})}/><Field label="Chức danh người ký" value={d.signature_title||''} onChangeText={v=>setD({...d,signature_title:v})}/></Card><AppButton title="Lưu hồ sơ công ty" icon="content-save" onPress={()=>void saveCompany(d).then(()=>Alert.alert('Đã lưu','Hồ sơ công ty đã được lưu offline.'))}/></Screen>}
function Media({title,path,gallery,camera}:{title:string;path:string;gallery:()=>void;camera:()=>void}){return <Card><SectionTitle>{title}</SectionTitle><Row><ImageThumb path={path} size={120}/><View style={{flex:1,gap:8}}><AppButton variant="secondary" title="Chọn ảnh" icon="image-plus" onPress={gallery}/><AppButton variant="secondary" title="Chụp ảnh" icon="camera" onPress={camera}/></View></Row></Card>}
