import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { AppButton, Card, Chips, Divider, Field, ImageThumb, Muted, Row, SectionTitle, ToggleRow, IconButton } from '@/components/ui';
import { colors } from '@/constants/theme';
import { documentLineAmount, getLiveState, newDocument, pricingBreakdown, saveDocument, saveLiveState, visibleItems } from '@/services/documentEngine';
import { listProducts } from '@/services/products';
import { makeId, today } from '@/services/id';
import { pickImages } from '@/services/media';

const money=(v:any)=>`${Math.round(Number(v||0)).toLocaleString('vi-VN')} đ`;
export default function DocumentEditor(){const params=useLocalSearchParams<any>();const [state,setState]=useState<any>(null);const [products,setProducts]=useState<any[]>([]);const [picker,setPicker]=useState(false);const [manual,setManual]=useState(false);const [draft,setDraft]=useState<any>({name:'',unit:'m²',qty:'1',price:'0',description:'',image:''});const [saving,setSaving]=useState(false);
useEffect(()=>{void (async()=>{const st=params.new==='1'?await newDocument(params.mode==='invoice'?'invoice':'quote'):await getLiveState();setState(st);setProducts(await listProducts())})()},[]);
const p=state?.project||{};const breakdown=useMemo(()=>state?pricingBreakdown(state):null,[state]);const rows=state?visibleItems(state):[];
const commit=(next:any)=>{setState({...next});void saveLiveState(next)};const setProject=(patch:any)=>commit({...state,project:{...p,...patch}});const setPricing=(patch:any)=>setProject({pricing:{...(p.pricing||{}),...patch}});const setTerms=(patch:any)=>setProject({payment_terms:{...(p.payment_terms||{}),...patch}});const setSigning=(patch:any)=>setProject({signing:{...(p.signing||{}),...patch}});
const ensureRoom=(st:any)=>{const next=JSON.parse(JSON.stringify(st));if(!next.floors?.length)next.floors=[{id:makeId('FLR'),name:'Hạng mục',rooms:[]}];if(!next.floors[0].rooms?.length)next.floors[0].rooms=[{id:makeId('ROM'),name:'Chung',items:[]}];return next};
const addProduct=(prod:any)=>{let next=ensureRoom(state);next.floors[0].rooms[0].items.push({id:makeId('ITM'),name:prod.name,unit:prod.unit||'m²',qty:1,unit_price:Number(prod.price||0),price:Number(prod.price||0),image:prod.image||'',description:prod.description||'',product_id:prod.id});commit(next);setPicker(false)};
const addManual=()=>{if(!draft.name.trim())return Alert.alert('Thiếu tên','Nhập tên hạng mục.');let next=ensureRoom(state);next.floors[0].rooms[0].items.push({id:makeId('ITM'),name:draft.name,unit:draft.unit||'m²',qty:Number(draft.qty||1),unit_price:Number(draft.price||0),price:Number(draft.price||0),description:draft.description,image:draft.image});commit(next);setManual(false);setDraft({name:'',unit:'m²',qty:'1',price:'0',description:'',image:''})};
const patchItem=(id:string,patch:any)=>{const next=JSON.parse(JSON.stringify(state));for(const f of next.floors||[])for(const r of f.rooms||[])for(const it of r.items||[])if(it.id===id)Object.assign(it,patch);commit(next)};const removeItem=(id:string)=>{const next=JSON.parse(JSON.stringify(state));for(const f of next.floors||[])for(const r of f.rooms||[])r.items=(r.items||[]).filter((it:any)=>it.id!==id);commit(next)};
const save=async()=>{setSaving(true);try{const e=await saveDocument(state);setState(e.state);Alert.alert('Đã lưu',`${e.meta.document_no||''} đã được lưu offline.`)}catch(e:any){Alert.alert('Lỗi',e.message||String(e))}finally{setSaving(false)}};
if(!state)return <Screen title="Chứng từ"><Card><Text>Đang mở dữ liệu…</Text></Card></Screen>;
return <Screen title={state.document_mode==='invoice'?'Hóa đơn':'Báo giá'} subtitle="Soạn chứng từ đầy đủ • tự động lưu bản nháp" right={<IconButton icon="close" onPress={()=>router.back()}/>}>
<Chips value={state.document_mode} onChange={async(v)=>{const n=await newDocument(v as any);setState(n)}} options={[{value:'quote',label:'Báo giá'},{value:'invoice',label:'Hóa đơn'}]}/>
<Card><SectionTitle>Thông tin khách hàng / công trình</SectionTitle><Field label="Khách hàng" value={p.customer} onChangeText={v=>setProject({customer:v})}/><Field label="Địa chỉ / công trình" value={p.address} onChangeText={v=>setProject({address:v,project_name:v})}/><Row><View style={{flex:1}}><Field label="Mã khách" value={p.customer_code} onChangeText={v=>setProject({customer_code:v})}/></View><View style={{flex:1}}><Field label="Mã công trình" value={p.project_code} onChangeText={v=>setProject({project_code:v})}/></View></Row><Row><View style={{flex:1}}><Field label="Số chứng từ" value={p.quote_no} onChangeText={v=>setProject({quote_no:v})}/></View><View style={{flex:1}}><Field label="Ngày" value={p.quote_date||today()} onChangeText={v=>setProject({quote_date:v})}/></View></Row>{state.document_mode==='quote'?<Row><View style={{flex:1}}><Field label="Hiệu lực (ngày)" keyboardType="numeric" value={p.validity_days||30} onChangeText={v=>setProject({validity_days:Number(v||0)})}/></View><View style={{flex:1}}><Field label="Hạn báo giá" value={p.valid_until} onChangeText={v=>setProject({valid_until:v})}/></View></Row>:null}<Field label="Ghi chú" multiline value={p.quote_note} onChangeText={v=>setProject({quote_note:v})}/></Card>
<SectionTitle right={<Row><IconButton icon="package-variant" label="Thư viện" onPress={()=>setPicker(true)}/><IconButton icon="plus" label="Thủ công" onPress={()=>setManual(true)}/></Row>}>Hạng mục ({rows.length})</SectionTitle>
{rows.map(({floor,room,item}:any)=><Card key={item.id}><Row><ImageThumb path={item.image} size={64}/><View style={{flex:1}}><Text style={s.itemName}>{item.name}</Text><Muted>{floor} › {room} • {item.unit||''}</Muted><Text style={s.amount}>{money(documentLineAmount(item))}</Text></View><IconButton icon="trash-can-outline" color={colors.danger} onPress={()=>removeItem(item.id)}/></Row><Row><View style={{flex:1}}><Field label="Khối lượng" keyboardType="decimal-pad" value={item.qty} onChangeText={v=>patchItem(item.id,{qty:Number(v.replace(',','.')||0)})}/></View><View style={{flex:1}}><Field label="Đơn giá" keyboardType="numeric" value={item.unit_price??item.price} onChangeText={v=>patchItem(item.id,{unit_price:Number(v.replace(/\D/g,'')||0)})}/></View></Row><Field label="Mô tả" value={item.description||''} onChangeText={v=>patchItem(item.id,{description:v})}/><AppButton compact variant="secondary" icon="image-edit-outline" title="Đổi/thêm ảnh" onPress={()=>void pickImages({ownerType:'DOCUMENT_ITEM',ownerId:item.id,multiple:false}).then(a=>{if(a[0])patchItem(item.id,{image:a[0].uri})})}/></Card>)}
{!rows.length?<Card><Muted>Chưa có hạng mục. Chọn từ thư viện sản phẩm hoặc thêm thủ công.</Muted></Card>:null}
<Card><SectionTitle>Chiết khấu • phụ phí • VAT</SectionTitle><ToggleRow label="Chiết khấu" value={!!p.pricing?.discount_enabled} onChange={v=>setPricing({discount_enabled:v})}/>{p.pricing?.discount_enabled?<><Chips value={p.pricing.discount_type||'percent'} onChange={v=>setPricing({discount_type:v})} options={[{value:'percent',label:'%'},{value:'fixed',label:'Số tiền'}]}/><Field label="Giá trị chiết khấu" keyboardType="numeric" value={p.pricing.discount_value||0} onChangeText={v=>setPricing({discount_value:Number(v||0)})}/></>:null}<ToggleRow label="Phụ phí" value={!!p.pricing?.surcharge_enabled} onChange={v=>setPricing({surcharge_enabled:v})}/>{p.pricing?.surcharge_enabled?<><Field label="Tên phụ phí" value={p.pricing.surcharge_label||'Phụ phí'} onChangeText={v=>setPricing({surcharge_label:v})}/><Row><View style={{flex:1}}><Chips value={p.pricing.surcharge_type||'fixed'} onChange={v=>setPricing({surcharge_type:v})} options={[{value:'fixed',label:'Số tiền'},{value:'percent',label:'%'}]}/></View><View style={{flex:1}}><Field label="Giá trị" keyboardType="numeric" value={p.pricing.surcharge_value||0} onChangeText={v=>setPricing({surcharge_value:Number(v||0)})}/></View></Row></>:null}<ToggleRow label="VAT" value={!!p.pricing?.vat_enabled} onChange={v=>setPricing({vat_enabled:v})}/>{p.pricing?.vat_enabled?<Field label="VAT (%)" keyboardType="numeric" value={p.pricing.vat_rate??10} onChangeText={v=>setPricing({vat_rate:Number(v||0)})}/>:null}</Card>
<Card><SectionTitle>Thanh toán</SectionTitle><ToggleRow label="Hiển thị điều khoản thanh toán" value={!!p.payment_terms?.enabled} onChange={v=>setTerms({enabled:v})}/>{p.payment_terms?.enabled?<><Chips value={p.payment_terms.method||'bank_transfer'} onChange={v=>setTerms({method:v})} options={[{value:'bank_transfer',label:'Chuyển khoản'},{value:'cash',label:'Tiền mặt'},{value:'other',label:'Khác'}]}/><Field label="Đặt cọc" multiline value={p.payment_terms.deposit_terms||''} onChangeText={v=>setTerms({deposit_terms:v})}/><Field label="Các đợt thanh toán" multiline value={p.payment_terms.installment_terms||''} onChangeText={v=>setTerms({installment_terms:v})}/><Field label="Điều khoản bổ sung" multiline value={p.payment_terms.terms_text||''} onChangeText={v=>setTerms({terms_text:v})}/></>:null}</Card>
<Card><SectionTitle>Ký xác nhận</SectionTitle><ToggleRow label="Có chữ ký khách hàng" value={!!p.signing?.enabled} onChange={v=>setSigning({enabled:v})}/>{p.signing?.enabled?<><Field label="Người ký" value={p.signing.customer_name||''} onChangeText={v=>setSigning({customer_name:v})}/><Field label="Chức danh" value={p.signing.customer_title||''} onChangeText={v=>setSigning({customer_title:v})}/></>:null}<ToggleRow label="Hiện chữ ký công ty" value={p.signing?.show_company_signature!==false} onChange={v=>setSigning({show_company_signature:v})}/><ToggleRow label="Hiện con dấu" value={p.signing?.show_company_stamp!==false} onChange={v=>setSigning({show_company_stamp:v})}/></Card>
<Card><SectionTitle>Tổng tiền</SectionTitle><Sum k="Tạm tính" v={breakdown?.subtotal}/><Sum k="Chiết khấu" v={-Number(breakdown?.discount||0)}/><Sum k="Phụ phí" v={breakdown?.surcharge}/><Sum k="VAT" v={breakdown?.vat}/><Divider/><Sum k="THÀNH TIỀN" v={breakdown?.grand_total} strong/></Card>
<Row style={{flexWrap:'wrap'}}><AppButton title={saving?'Đang lưu…':'Lưu chứng từ'} disabled={saving} icon="content-save" onPress={()=>void save()}/><AppButton variant="secondary" title="Xem trước / Xuất" icon="file-eye-outline" onPress={()=>router.push('/document-preview')}/><AppButton variant="secondary" title="Đo đạc" icon="ruler-square" onPress={()=>router.push('/measurements')}/></Row>
<ProductPicker visible={picker} products={products} close={()=>setPicker(false)} pick={addProduct}/><Manual visible={manual} d={draft} setD={setDraft} close={()=>setManual(false)} add={addManual}/>
</Screen>}
function Sum({k,v,strong=false}:{k:string;v:any;strong?:boolean}){return <Row><Text style={[s.sumK,strong&&s.strong]}>{k}</Text><Text style={[s.sumV,strong&&s.strong]}>{money(v)}</Text></Row>}
function ProductPicker({visible,products,close,pick}:{visible:boolean;products:any[];close:()=>void;pick:(p:any)=>void}){const [q,setQ]=useState('');const rows=products.filter(x=>!q||String(x.name).toLowerCase().includes(q.toLowerCase())).slice(0,80);return <Modal visible={visible} animationType="slide"><Screen title="Chọn sản phẩm" right={<IconButton icon="close" onPress={close}/>}><Field label="Tìm kiếm" value={q} onChangeText={setQ}/>{rows.map(p=><TouchableOpacity key={p.id} onPress={()=>pick(p)}><Card><Row><ImageThumb path={p.image} size={52}/><View style={{flex:1}}><Text style={s.itemName}>{p.name}</Text><Muted>{p.unit||''} • {money(p.price)}</Muted></View><MaterialCommunityIcons name="plus-circle" size={24} color={colors.primary}/></Row></Card></TouchableOpacity>)}</Screen></Modal>}
function Manual({visible,d,setD,close,add}:{visible:boolean;d:any;setD:(v:any)=>void;close:()=>void;add:()=>void}){return <Modal visible={visible} animationType="slide"><Screen title="Thêm hạng mục" right={<IconButton icon="close" onPress={close}/>}><Field label="Tên hạng mục" value={d.name} onChangeText={v=>setD({...d,name:v})}/><Row><View style={{flex:1}}><Field label="Đơn vị" value={d.unit} onChangeText={v=>setD({...d,unit:v})}/></View><View style={{flex:1}}><Field label="Khối lượng" keyboardType="decimal-pad" value={d.qty} onChangeText={v=>setD({...d,qty:v})}/></View></Row><Field label="Đơn giá" keyboardType="numeric" value={d.price} onChangeText={v=>setD({...d,price:v})}/><Field label="Mô tả" multiline value={d.description} onChangeText={v=>setD({...d,description:v})}/><AppButton variant="secondary" title="Chọn ảnh" icon="image-plus" onPress={()=>void pickImages({ownerType:'DOCUMENT_ITEM',ownerId:'draft',multiple:false}).then(a=>a[0]&&setD({...d,image:a[0].uri}))}/>{d.image?<ImageThumb path={d.image} size={150}/>:null}<AppButton title="Thêm vào chứng từ" icon="plus" onPress={add}/></Screen></Modal>}
const s=StyleSheet.create({itemName:{fontWeight:'900',fontSize:14,color:colors.text},amount:{fontWeight:'900',color:colors.primary,marginTop:5},sumK:{flex:1,color:colors.textSoft},sumV:{fontWeight:'800',color:colors.text},strong:{fontWeight:'900',fontSize:16,color:colors.primary}});
