import { useEffect, useState } from 'react';
import { Alert, Modal, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen';
import { AppButton, Card, Chips, Field, IconButton, ImageThumb, Muted, Row, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';
import { listStockBalances, listStockTransactions, postStockMovement, stockIntegrity } from '@/services/retail';
export default function Inventory(){const [items,setItems]=useState<any[]>([]),[txs,setTxs]=useState<any[]>([]),[move,setMove]=useState<any>(null),[audit,setAudit]=useState<any>(null);const load=async()=>{setItems(await listStockBalances());setTxs(await listStockTransactions(50))};useEffect(()=>{void load()},[]);return <Screen title="Kho hàng" subtitle="Nhập • xuất • tồn • điều chỉnh" right={<IconButton icon="close" onPress={()=>router.back()}/>}><Row><AppButton variant="secondary" title="Kiểm tra sổ kho" icon="shield-search" onPress={()=>void stockIntegrity().then(setAudit)}/><AppButton variant="secondary" title="POS" icon="cash-register" onPress={()=>router.push('/retail')}/></Row>{audit?<Card><Text style={{fontWeight:'900',color:audit.ok?colors.success:colors.danger}}>{audit.ok?'Sổ kho khớp hoàn toàn':`${audit.errors?.length||0} SKU lệch tồn`}</Text></Card>:null}<SectionTitle>Tồn hiện tại ({items.length})</SectionTitle>{items.map(x=><Card key={x.sku_id}><Row><ImageThumb path={x.image} size={55}/><View style={{flex:1}}><Text style={s.name}>{x.product_name}</Text><Muted>{x.sku_code} • {x.unit}</Muted></View><View style={{alignItems:'flex-end'}}><Text style={[s.qty,Number(x.qty)<=0&&{color:colors.danger}]}>{Number(x.qty||0).toLocaleString('vi-VN')}</Text><Muted>Tồn</Muted></View></Row><Row><AppButton compact title="Nhập" icon="tray-arrow-down" onPress={()=>setMove({sku_id:x.sku_id,product_name:x.product_name,tx_type:'PURCHASE',qty:'',note:''})}/><AppButton compact variant="secondary" title="Xuất" icon="tray-arrow-up" onPress={()=>setMove({sku_id:x.sku_id,product_name:x.product_name,tx_type:'OUT',qty:'',note:''})}/><AppButton compact variant="secondary" title="Tồn đầu" icon="database-plus-outline" onPress={()=>setMove({sku_id:x.sku_id,product_name:x.product_name,tx_type:'OPENING',qty:'',note:'Tồn đầu kỳ'})}/></Row></Card>)}<SectionTitle>Biến động gần đây</SectionTitle>{txs.slice(0,30).map(t=><Card key={t.stock_tx_id}><Row><View style={{flex:1}}><Text style={s.name}>{t.product_name}</Text><Muted>{t.tx_type} • {t.occurred_at_utc} • {t.note||''}</Muted></View><Text style={{fontWeight:'900',color:Number(t.qty_delta_micros)>=0?colors.success:colors.danger}}>{(Number(t.qty_delta_micros||0)/1000000).toLocaleString('vi-VN')}</Text></Row></Card>)}<MoveModal value={move} close={()=>setMove(null)} save={async d=>{try{await postStockMovement({...d,qty:Number(d.qty||0)});setMove(null);await load()}catch(e:any){Alert.alert('Lỗi kho',e.message||String(e))}}}/></Screen>}
function MoveModal({value,close,save}:{value:any;close:()=>void;save:(v:any)=>void}){const [d,setD]=useState(value);useEffect(()=>setD(value),[value]);if(!d)return null;return <Modal visible animationType="slide"><Screen title="Biến động kho" subtitle={d.product_name} right={<IconButton icon="close" onPress={close}/>}><Chips value={d.tx_type} onChange={v=>setD({...d,tx_type:v})} options={[{value:'PURCHASE',label:'Nhập mua'},{value:'OUT',label:'Xuất khác'},{value:'ADJUST_IN',label:'Điều chỉnh +'},{value:'ADJUST_OUT',label:'Điều chỉnh -'},{value:'OPENING',label:'Tồn đầu'}]}/><Field label="Số lượng" keyboardType="decimal-pad" value={d.qty} onChangeText={v=>setD({...d,qty:v})}/><Field label="Ghi chú" multiline value={d.note} onChangeText={v=>setD({...d,note:v})}/><AppButton title="Ghi sổ kho" icon="content-save" onPress={()=>void save(d)}/></Screen></Modal>}
const s=StyleSheet.create({name:{fontWeight:'900',color:colors.text},qty:{fontWeight:'900',fontSize:20,color:colors.primary}});
