import { useEffect, useState } from 'react';
import { Alert, Modal, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen';
import { AppButton, Card, Chips, Field, IconButton, Muted, Row, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';
import { addPayment, listInvoiceSnapshots, listPaymentEntries, reversePayment } from '@/services/payments';
import { today } from '@/services/id';
const money=(v:any)=>`${Number(v||0).toLocaleString('vi-VN')} đ`;
export default function Payments(){const [invoices,setInvoices]=useState<any[]>([]),[entries,setEntries]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[reverseTarget,setReverseTarget]=useState<any>(null);const load=async()=>{setInvoices(await listInvoiceSnapshots());setEntries(await listPaymentEntries())};useEffect(()=>{void load()},[]);return <Screen title="Thanh toán & công nợ" subtitle="Theo dõi hóa đơn, thu tiền và hoàn tác" right={<IconButton icon="close" onPress={()=>router.back()}/>}><View style={s.metrics}><Card style={s.m}><Muted>Tổng phải thu</Muted><Text style={s.v}>{money(invoices.reduce((a,x)=>a+x.total,0))}</Text></Card><Card style={s.m}><Muted>Còn nợ</Muted><Text style={s.v}>{money(invoices.reduce((a,x)=>a+x.remaining,0))}</Text></Card></View>{invoices.map(x=><Card key={x.id}><Row><View style={{flex:1}}><Text style={s.no}>{x.document_no}</Text><Text style={s.name}>{x.customer||'Khách lẻ'}</Text><Muted>{x.project} • {x.status}</Muted></View><View style={{alignItems:'flex-end'}}><Text style={s.debt}>{money(x.remaining)}</Text><Muted>đã thu {money(x.received)}</Muted></View></Row><AppButton compact title="Ghi nhận thanh toán" icon="cash-plus" onPress={()=>setSelected(x)}/>{entries.filter(e=>e.invoice_id===x.id).slice(0,5).map(e=><Row key={e.id}><Muted>{e.date} • {e.method} • {e.type}</Muted><Text style={{marginLeft:'auto',fontWeight:'800',color:e.amount<0?colors.danger:colors.success}}>{money(e.amount)}</Text>{e.type==='PAYMENT'?<IconButton icon="undo" color={colors.danger} onPress={()=>setReverseTarget(e)}/>:null}</Row>)}</Card>)}<PaymentModal invoice={selected} close={()=>setSelected(null)} save={async(v)=>{try{await addPayment(v);setSelected(null);await load()}catch(e:any){Alert.alert('Lỗi',e.message||String(e))}}}/><ReversalModal entry={reverseTarget} close={()=>setReverseTarget(null)} save={async(reason,date)=>{try{await reversePayment(reverseTarget.id,reason,date);setReverseTarget(null);await load()}catch(e:any){Alert.alert('Lỗi',e.message||String(e))}}}/></Screen>}

function ReversalModal({entry,close,save}:{entry:any;close:()=>void;save:(reason:string,date:string)=>void}){const [reason,setReason]=useState(''),[date,setDate]=useState(today());useEffect(()=>{if(entry){setReason('');setDate(today())}},[entry]);if(!entry)return null;return <Modal visible animationType="slide"><Screen title="Hoàn tác thanh toán" subtitle={entry.document_no||'Khoản thanh toán'} right={<IconButton icon="close" onPress={close}/>}><Card><SectionTitle>Khoản cần hoàn tác</SectionTitle><Muted>{entry.date} • {entry.method}</Muted><Text style={s.reverseAmount}>{money(entry.amount)}</Text><Field label="Ngày điều chỉnh" value={date} onChangeText={setDate}/><Field label="Lý do hủy/điều chỉnh" value={reason} onChangeText={setReason} multiline/><AppButton title="Xác nhận hoàn tác" icon="undo" onPress={()=>{if(!reason.trim()){Alert.alert('Thiếu lý do','Hãy nhập lý do hủy/điều chỉnh.');return}void save(reason.trim(),date)}}/><AppButton variant="secondary" title="Đóng" onPress={close}/></Card></Screen></Modal>}
function PaymentModal({invoice,close,save}:{invoice:any;close:()=>void;save:(v:any)=>void}){const [d,setD]=useState<any>({amount:'',date:today(),method:'CK',note:''});useEffect(()=>setD({amount:invoice?String(invoice.remaining||''):'',date:today(),method:'CK',note:''}),[invoice]);if(!invoice)return null;return <Modal visible animationType="slide"><Screen title="Ghi nhận thanh toán" subtitle={invoice.document_no} right={<IconButton icon="close" onPress={close}/>}><Card><Text style={s.name}>{invoice.customer}</Text><Muted>Còn phải thu: {money(invoice.remaining)}</Muted><Field label="Số tiền" keyboardType="numeric" value={d.amount} onChangeText={v=>setD({...d,amount:v.replace(/\D/g,'')})}/><Field label="Ngày" value={d.date} onChangeText={v=>setD({...d,date:v})}/><Chips value={d.method} onChange={v=>setD({...d,method:v})} options={[{value:'CK',label:'Chuyển khoản'},{value:'TIỀN MẶT',label:'Tiền mặt'},{value:'KHÁC',label:'Khác'}]}/><Field label="Ghi chú" value={d.note} onChangeText={v=>setD({...d,note:v})}/><AppButton title="Lưu thanh toán" icon="content-save" onPress={()=>void save({invoice_id:invoice.id,amount:Number(d.amount||0),date:d.date,method:d.method,note:d.note})}/></Card></Screen></Modal>}
const s=StyleSheet.create({metrics:{flexDirection:'row',gap:8},m:{width:'49%'},v:{fontSize:17,fontWeight:'900',color:colors.text},no:{fontWeight:'900',color:colors.primary},name:{fontWeight:'900',color:colors.text},debt:{fontWeight:'900',color:colors.danger},reverseAmount:{fontSize:22,fontWeight:'900',color:colors.danger,marginVertical:10}});
