import { useEffect, useState } from 'react';
import { Alert, Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen';
import { AppButton, Card, Chips, Field, IconButton, ImageThumb, Muted, Row, SectionTitle, ToggleRow, confirm } from '@/components/ui';
import { colors } from '@/constants/theme';
import { deleteProduct, deleteProductGroup, listProductGroups, listProducts, saveProduct, saveProductGroup, setProductFavorite, setProductHidden } from '@/services/products';
import { pickImages, takePhoto } from '@/services/media';
const money=(v:any)=>`${Number(v||0).toLocaleString('vi-VN')} đ`;
export default function Products(){const [items,setItems]=useState<any[]>([]),[groups,setGroups]=useState<any[]>([]),[q,setQ]=useState(''),[group,setGroup]=useState(''),[edit,setEdit]=useState<any>(null),[groupModal,setGroupModal]=useState(false);const load=async()=>{setItems(await listProducts(q,group));setGroups(await listProductGroups())};useEffect(()=>{void load()},[q,group]);
return <Screen title="Thư viện sản phẩm" subtitle="Nhóm • hình ảnh • đơn giá • dữ liệu offline" right={<IconButton icon="close" onPress={()=>router.back()}/>}><Field label="Tìm sản phẩm" value={q} onChangeText={setQ}/><Row style={{flexWrap:'wrap'}}><Chips value={group} onChange={setGroup} options={[{value:'',label:'Tất cả'},...groups.slice(0,12).map(g=>({value:g.id,label:g.name}))]}/></Row><Row><AppButton title="Thêm sản phẩm" icon="plus" onPress={()=>setEdit({name:'',unit:'m²',price:0,group_id:group,image:'',description:'',favorite:false,hidden:false})}/><AppButton variant="secondary" title="Nhóm" icon="folder-cog-outline" onPress={()=>setGroupModal(true)}/></Row>
{items.map(p=><TouchableOpacity key={p.id} onPress={()=>setEdit({...p})}><Card><Row><ImageThumb path={p.image} size={68}/><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Muted>{p.unit||''} • {groups.find(g=>g.id===p.group_id)?.name||'Chưa nhóm'}</Muted><Text style={s.price}>{money(p.price)}</Text></View><IconButton icon={p.favorite?'star':'star-outline'} color={p.favorite?'#D79B00':colors.textSoft} onPress={()=>void setProductFavorite(p.id,!p.favorite).then(load)}/></Row>{p.hidden?<Text style={s.hidden}>Đang ẩn khỏi thư viện chọn nhanh</Text>:null}</Card></TouchableOpacity>)}
<ProductForm value={edit} groups={groups} close={()=>setEdit(null)} saved={async(v)=>{await saveProduct(v);setEdit(null);await load()}} remove={edit?.id?()=>confirm('Xóa sản phẩm','Xóa sản phẩm khỏi thư viện?',()=>void deleteProduct(edit.id).then(()=>{setEdit(null);return load()})):undefined}/><GroupManager visible={groupModal} groups={groups} close={()=>setGroupModal(false)} reload={load}/></Screen>}
function ProductForm({value,groups,close,saved,remove}:{value:any;groups:any[];close:()=>void;saved:(v:any)=>void;remove?:()=>void}){const [d,setD]=useState(value);useEffect(()=>setD(value),[value]);if(!d)return null;return <Modal visible animationType="slide"><Screen title={d.id?'Sửa sản phẩm':'Thêm sản phẩm'} right={<IconButton icon="close" onPress={close}/>}><Card><Row><ImageThumb path={d.image} size={120}/><View style={{flex:1,gap:8}}><AppButton compact variant="secondary" title="Thư viện ảnh" icon="image-plus" onPress={()=>void pickImages({ownerType:'PRODUCT',ownerId:d.id||'new',multiple:false}).then(a=>a[0]&&setD({...d,image:a[0].uri}))}/><AppButton compact variant="secondary" title="Chụp ảnh" icon="camera" onPress={()=>void takePhoto('PRODUCT',d.id||'new').then(a=>a&&setD({...d,image:a.uri}))}/></View></Row><Field label="Tên sản phẩm" value={d.name} onChangeText={v=>setD({...d,name:v})}/><Row><View style={{flex:1}}><Field label="Đơn vị" value={d.unit} onChangeText={v=>setD({...d,unit:v})}/></View><View style={{flex:1}}><Field label="Đơn giá" keyboardType="numeric" value={d.price} onChangeText={v=>setD({...d,price:Number(v.replace(/\D/g,'')||0)})}/></View></Row><Text style={s.label}>Nhóm</Text><Chips value={d.group_id||''} onChange={v=>setD({...d,group_id:v})} options={[{value:'',label:'Chưa nhóm'},...groups.map(g=>({value:g.id,label:g.name}))]}/><Field label="Mô tả" multiline value={d.description||''} onChangeText={v=>setD({...d,description:v})}/><ToggleRow label="Yêu thích" value={!!d.favorite} onChange={v=>setD({...d,favorite:v})}/><ToggleRow label="Ẩn sản phẩm" value={!!d.hidden} onChange={v=>setD({...d,hidden:v})}/><AppButton title="Lưu sản phẩm" icon="content-save" onPress={()=>void saved(d)}/>{remove?<AppButton variant="danger" title="Xóa sản phẩm" icon="trash-can-outline" onPress={remove}/>:null}</Card></Screen></Modal>}
function GroupManager({visible,groups,close,reload}:{visible:boolean;groups:any[];close:()=>void;reload:()=>void}){const [name,setName]=useState('');return <Modal visible={visible} animationType="slide"><Screen title="Nhóm sản phẩm" right={<IconButton icon="close" onPress={close}/>}><Card><Field label="Tên nhóm mới" value={name} onChangeText={setName}/><AppButton title="Thêm nhóm" icon="folder-plus-outline" onPress={()=>void saveProductGroup({name}).then(()=>{setName('');return reload()}).catch(e=>Alert.alert('Lỗi',String(e.message||e)))}/></Card>{groups.map(g=><Card key={g.id}><Row><Text style={{flex:1,fontWeight:'900',color:colors.text}}>{g.name}</Text><IconButton icon="trash-can-outline" color={colors.danger} onPress={()=>confirm('Xóa nhóm','Sản phẩm trong nhóm sẽ cần chuyển nhóm nếu có.',()=>void deleteProductGroup(g.id).then(reload).catch(e=>Alert.alert('Không thể xóa',String(e.message||e))))}/></Row></Card>)}</Screen></Modal>}
const s=StyleSheet.create({name:{fontWeight:'900',fontSize:15,color:colors.text},price:{fontWeight:'900',color:colors.primary,marginTop:5},hidden:{fontSize:10,color:colors.danger,fontWeight:'800'},label:{fontSize:12,fontWeight:'800',color:colors.text}});
