import { useEffect, useState } from 'react';
import { Alert, Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Screen } from '@/components/Screen';
import { AppButton, Card, Field, IconButton, ImageThumb, Muted, Row, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';
import { addQuickManual, addQuickProduct, applyQuickToDocument, getQuick, removeQuickItem, saveQuick, updateQuickItem } from '@/services/quick';
import { listProducts } from '@/services/products';
import { pickImages, takePhoto } from '@/services/media';
export default function Quick(){const {kind='quote'}=useLocalSearchParams<any>();const k=kind==='invoice'?'invoice':'quote';const [q,setQ]=useState<any>(null),[products,setProducts]=useState<any[]>([]),[picker,setPicker]=useState(false),[manual,setManual]=useState(false);const load=async()=>{setQ(await getQuick(k));setProducts(await listProducts())};useEffect(()=>{void load()},[k]);if(!q)return <Screen title="Tạo nhanh"><Card><Text>Đang tải…</Text></Card></Screen>;const patch=(p:any)=>{const n={...q,...p};setQ(n);void saveQuick(k,n)};const info=(p:any)=>patch({info:{...(q.info||{}),...p}});return <Screen title={k==='quote'?'Báo giá nhanh':'Hóa đơn nhanh'} subtitle="Nhập ít bước, dùng ngay offline" right={<IconButton icon="close" onPress={()=>router.back()}/>}><Card><SectionTitle>Thông tin</SectionTitle><Field label="Khách hàng" value={q.info?.customer||''} onChangeText={v=>info({customer:v})}/><Field label="Địa chỉ / công trình" value={q.info?.address||''} onChangeText={v=>info({address:v})}/><Field label="Điện thoại" value={q.info?.phone||''} onChangeText={v=>info({phone:v})}/><Field label="Tiêu đề bảng" value={q.info?.title||''} onChangeText={v=>info({title:v})}/><Field label="Ghi chú" multiline value={q.info?.note||''} onChangeText={v=>info({note:v})}/></Card><Row><AppButton title="Chọn sản phẩm" icon="package-variant" onPress={()=>setPicker(true)}/><AppButton variant="secondary" title="Thêm thủ công" icon="plus" onPress={()=>setManual(true)}/></Row><SectionTitle>Hạng mục ({q.items?.length||0})</SectionTitle>{(q.items||[]).map((it:any)=><Card key={it.id}><Row><ImageThumb path={it.image} size={58}/><View style={{flex:1}}><Text style={s.name}>{it.name}</Text><Muted>{it.unit} • {Number(it.price||0).toLocaleString('vi-VN')} đ</Muted></View><IconButton icon="trash-can-outline" color={colors.danger} onPress={()=>void removeQuickItem(k,it.id).then(load)}/></Row><Row><View style={{flex:1}}><Field label="SL/KL" keyboardType="decimal-pad" value={it.qty} onChangeText={v=>void updateQuickItem(k,it.id,{qty:Number(v.replace(',','.')||0)}).then(load)}/></View><View style={{flex:1}}><Field label="Đơn giá" keyboardType="numeric" value={it.price} onChangeText={v=>void updateQuickItem(k,it.id,{price:Number(v.replace(/\D/g,'')||0)}).then(load)}/></View></Row></Card>)}<Card><Text style={s.total}>Tổng tạm tính: {(q.items||[]).reduce((a:number,x:any)=>a+Number(x.qty||0)*Number(x.price||0),0).toLocaleString('vi-VN')} đ</Text></Card><AppButton title="Chuyển sang chứng từ đầy đủ" icon="arrow-right-bold" onPress={()=>void applyQuickToDocument(k).then(()=>router.replace('/document-editor')).catch(e=>Alert.alert('Lỗi',String(e.message||e)))}/><Picker visible={picker} rows={products} close={()=>setPicker(false)} pick={async p=>{await addQuickProduct(k,p.id);setPicker(false);await load()}}/><Manual visible={manual} close={()=>setManual(false)} add={async d=>{await addQuickManual(k,d);setManual(false);await load()}}/></Screen>}
function Picker({visible,rows,close,pick}:{visible:boolean;rows:any[];close:()=>void;pick:(p:any)=>void}){const [q,setQ]=useState('');return <Modal visible={visible} animationType="slide"><Screen title="Chọn sản phẩm" right={<IconButton icon="close" onPress={close}/>}><Field label="Tìm" value={q} onChangeText={setQ}/>{rows.filter(x=>!q||x.name.toLowerCase().includes(q.toLowerCase())).slice(0,100).map(p=><TouchableOpacity key={p.id} onPress={()=>void pick(p)}><Card><Row><ImageThumb path={p.image} size={50}/><View style={{flex:1}}><Text style={s.name}>{p.name}</Text><Muted>{p.unit} • {Number(p.price||0).toLocaleString('vi-VN')} đ</Muted></View></Row></Card></TouchableOpacity>)}</Screen></Modal>}
function Manual({visible,close,add}:{visible:boolean;close:()=>void;add:(d:any)=>void}){const [d,setD]=useState<any>({name:'',unit:'cái',qty:'1',price:'0',description:'',image:''});return <Modal visible={visible} animationType="slide"><Screen title="Hạng mục thủ công" right={<IconButton icon="close" onPress={close}/>}><Field label="Tên" value={d.name} onChangeText={v=>setD({...d,name:v})}/><Row><View style={{flex:1}}><Field label="Đơn vị" value={d.unit} onChangeText={v=>setD({...d,unit:v})}/></View><View style={{flex:1}}><Field label="Số lượng" keyboardType="decimal-pad" value={d.qty} onChangeText={v=>setD({...d,qty:v})}/></View></Row><Field label="Đơn giá" keyboardType="numeric" value={d.price} onChangeText={v=>setD({...d,price:v})}/><Field label="Mô tả" multiline value={d.description} onChangeText={v=>setD({...d,description:v})}/><Row><AppButton variant="secondary" title="Chọn ảnh" icon="image" onPress={()=>void pickImages({ownerType:'QUICK_ITEM',ownerId:'draft',multiple:false}).then(a=>a[0]&&setD({...d,image:a[0].uri}))}/><AppButton variant="secondary" title="Chụp" icon="camera" onPress={()=>void takePhoto('QUICK_ITEM','draft').then(a=>a&&setD({...d,image:a.uri}))}/></Row>{d.image?<ImageThumb path={d.image} size={140}/>:null}<AppButton title="Thêm" icon="plus" onPress={()=>void add({...d,qty:Number(d.qty||1),price:Number(d.price||0)})}/></Screen></Modal>}
const s=StyleSheet.create({name:{fontWeight:'900',color:colors.text},total:{fontWeight:'900',fontSize:18,color:colors.primary,textAlign:'right'}});
