import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Clipboard from 'expo-clipboard';
import * as FileSystem from 'expo-file-system/legacy';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Linking, Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

import { Screen } from '@/components/Screen';
import { AppButton, Card, Chips, Divider, Field, IconButton, ImageThumb, Muted, Row, SectionTitle, ToggleRow, confirm } from '@/components/ui';
import { colors } from '@/constants/theme';
import { array, object } from '@/db/database';
import { SMART_INVOICE_PROMPT, SMART_QUOTE_PROMPT } from '@/services/aiJson';
import { applyDirectToDocument } from '@/services/directMeasurements';
import { getLiveState, newDocument, prepareSmartDocument, pricingBreakdown, saveDocument, saveLiveState, visibleItems } from '@/services/documentEngine';
import { pickDocument, pickImages, pickMultipleDocuments, takePhoto } from '@/services/media';
import { listProducts } from '@/services/products';
import { addSourceFromAttachment, clearSources, deleteSource, getSmartStats, importSmartJsonFile, importSmartText, listSources, moveSource, setPastedJson, setScopeNote, setSmartStage } from '@/services/sources';
import { makeId, today } from '@/services/id';

const STAGES = [
  { key: 'source', label: 'Nguồn', no: 1 },
  { key: 'process', label: 'Chuẩn hóa', no: 2 },
  { key: 'items', label: 'Hạng mục', no: 3 },
  { key: 'details', label: 'Thông tin', no: 4 },
  { key: 'preview', label: 'Xem trước', no: 5 },
] as const;
type Stage = typeof STAGES[number]['key'];
const money=(v:any)=>`${Math.round(Number(v||0)).toLocaleString('vi-VN')} đ`;

export default function SmartDocument() {
  const params = useLocalSearchParams<{ mode?: string; new?: string }>();
  const [state, setState] = useState<any>(null);
  const [stage, setStageLocal] = useState<Stage>('source');
  const [sources, setSources] = useState<any[]>([]);
  const [paste, setPaste] = useState('');
  const [busy, setBusy] = useState(false);
  const [picker, setPicker] = useState(false);
  const [products, setProducts] = useState<any[]>([]);
  const [importStatus, setImportStatus] = useState('Chưa dán kết quả.');

  useEffect(() => { void (async () => {
    let st = await getLiveState();
    if (params.new === '1' || !object(st.new_document).workflow_version) st = await newDocument(params.mode === 'invoice' ? 'invoice' : 'quote');
    if (params.mode && String(st.document_mode) !== params.mode) { st.document_mode = params.mode === 'invoice' ? 'invoice' : 'quote'; await saveLiveState(st); }
    setState(st);
    const nd = object(st.new_document);
    setStageLocal(STAGES.some(x => x.key === nd.stage) ? nd.stage as Stage : 'source');
    setPaste(String(nd.pasted_json || ''));
    setSources(await listSources());
    setProducts(await listProducts());
  })().catch(e => Alert.alert('Không mở được chứng từ thông minh', e?.message || String(e))); }, [params.mode, params.new]);

  const commit = async (next:any) => { setState({...next}); await saveLiveState(next); };
  const go = async (next:Stage) => { try { await setSmartStage(next); setStageLocal(next); } catch(e:any) { Alert.alert('Không chuyển được bước', e.message || String(e)); } };
  const refreshSources = async () => setSources(await listSources());
  const p = object(state?.project);
  const stats = useMemo(() => getSmartStats(state || {}), [state]);
  const rows = useMemo(() => visibleItems(state || {}), [state]);
  const totals = useMemo(() => pricingBreakdown(state || {}), [state]);

  const sourceCamera = async () => { try { const a = await takePhoto('SMART_SOURCE', 'draft'); if(a){await addSourceFromAttachment(a); await refreshSources();} } catch(e:any){Alert.alert('Không chụp được ảnh', e.message || String(e));} };
  const sourceImages = async () => { try { const xs = await pickImages({multiple:true, ownerType:'SMART_SOURCE', ownerId:'draft'}); for(const x of xs) await addSourceFromAttachment(x); await refreshSources(); } catch(e:any){Alert.alert('Không chọn được ảnh', e.message || String(e));} };
  const sourceDocs = async () => { try { const xs = await pickMultipleDocuments('SMART_SOURCE','draft',['application/pdf','image/*']); for(const x of xs) await addSourceFromAttachment(x); await refreshSources(); } catch(e:any){Alert.alert('Không chọn được tệp', e.message || String(e));} };
  const sourceJson = async () => { try { const x:any = await pickDocument('SMART_SOURCE','draft',['application/json','text/plain']); if(!x)return; await addSourceFromAttachment(x); await refreshSources(); setBusy(true); const result = await importSmartJsonFile(x.uri); setState(result.state); setPaste(await FileSystem.readAsStringAsync(x.uri)); await go('process'); } catch(e:any){Alert.alert('JSON không hợp lệ', e.message || String(e));} finally {setBusy(false);} };
  const prompt = state?.document_mode === 'invoice' ? SMART_INVOICE_PROMPT : SMART_QUOTE_PROMPT;
  const copyPrompt = async () => { try { await Clipboard.setStringAsync(prompt); setImportStatus('✓ Đã sao chép Prompt. Bước tiếp theo: mở ChatGPT và gửi ảnh/tệp nguồn.'); } catch(e:any) { Alert.alert('Không sao chép được Prompt', e.message || String(e)); } };
  const openChatGPT = async () => { try { await Linking.openURL('https://chatgpt.com/'); } catch { Alert.alert('Không mở được ChatGPT', 'Hãy mở ứng dụng ChatGPT hoặc trình duyệt và truy cập chatgpt.com.'); } };
  const pasteClipboard = async () => { try { const value=await Clipboard.getStringAsync(); if(!value.trim())throw new Error('Bộ nhớ tạm đang trống'); setPaste(value); await setPastedJson(value); setImportStatus('Đã dán nội dung. Bấm “Kiểm tra & nạp kết quả”.'); } catch(e:any) { Alert.alert('Không dán được từ bộ nhớ tạm', e.message || String(e)); } };
  const clearPaste = async () => { try { setPaste(''); await setPastedJson(''); setImportStatus('Chưa dán kết quả.'); } catch(e:any) { Alert.alert('Không xóa được nội dung', e.message || String(e)); } };
  const importPaste = async () => { if(!paste.trim())return Alert.alert('Chưa có dữ liệu','Dán kết quả JSON từ ChatGPT vào ô trước.'); try {setBusy(true);setImportStatus('Đang tìm JSON và kiểm tra dữ liệu…'); await setPastedJson(paste); const result=await importSmartText(paste); setState(result.state); const v=result.validation; setImportStatus(`✓ Đã nhận dữ liệu: ${v?.stats?.floors||0} tầng • ${v?.stats?.rooms||0} phòng • ${v?.stats?.items||0} hạng mục • NEED_CHECK ${v?.stats?.need_check||0}`); } catch(e:any){setImportStatus(`⚠ ${e.message||String(e)}`);Alert.alert('Dữ liệu nhập không hợp lệ', e.message || String(e));} finally{setBusy(false);} };
  const fromDirect = async () => { try { setBusy(true); const next = await applyDirectToDocument(state?.document_mode === 'quote' ? 'quote' : 'invoice'); let count=0; for(const f of array(next.floors))for(const r of array(f.rooms))for(const it of array(r.items)){it.id=it.id||it._direct_uid||makeId('ITM');if(String(it.name||'').trim()&&Number(it.qty)>0)count++;} if(!count)throw new Error('Không đọc được dữ liệu đo trực tiếp'); await saveLiveState(next); setState(next); await go('process'); } catch(e:any){Alert.alert('Không đọc được dữ liệu đo trực tiếp',e.message||String(e));} finally{setBusy(false);} };
  const addManual = async () => { const next=JSON.parse(JSON.stringify(state)); if(!array(next.floors).length)next.floors=[{id:makeId('FLR'),name:'Hạng mục',rooms:[{id:makeId('ROM'),name:'Chung',items:[]}]}]; if(!array(next.floors[0].rooms).length)next.floors[0].rooms=[{id:makeId('ROM'),name:'Chung',items:[]}]; next.floors[0].rooms[0].items.push({id:makeId('ITM'),name:'Hạng mục mới',qty:1,unit:'',unit_price:0,price:0,status:'NEED_CHECK',confidence:'MANUAL',source:'MANUAL'}); await commit(next); await go('items'); };

  const patchItem = async (id:string, patch:any) => { const next=JSON.parse(JSON.stringify(state)); for(const f of array(next.floors))for(const r of array(f.rooms))for(const it of array(r.items))if(it.id===id)Object.assign(it,patch); await commit(next); };
  const removeItem = async (id:string) => { const next=JSON.parse(JSON.stringify(state)); for(const f of array(next.floors))for(const r of array(f.rooms))r.items=array(r.items).filter((it:any)=>it.id!==id); await commit(next); };
  const addProduct = async (prod:any) => { const next=JSON.parse(JSON.stringify(state)); if(!array(next.floors).length)next.floors=[{id:makeId('FLR'),name:'Hạng mục',rooms:[]}]; if(!array(next.floors[0].rooms).length)next.floors[0].rooms=[{id:makeId('ROM'),name:'Chung',items:[]}]; next.floors[0].rooms[0].items.push({id:makeId('ITM'),name:prod.name||'Sản phẩm',qty:1,unit:prod.unit||'',unit_price:Number(prod.price||0),price:Number(prod.price||0),image:prod.image||'',description:prod.description||'',library_id:prod.id,status:'LOCKED',confidence:'HIGH',source:'PRODUCT_LIBRARY'}); await commit(next); setPicker(false); };
  const setProject = async (patch:any) => commit({...state,project:{...p,...patch}});
  const setPricing = async (patch:any) => setProject({pricing:{...object(p.pricing),...patch}});

  const handoff = async (nextRoute:'/document-editor'|'/document-preview') => { try { setBusy(true); const mode=state?.document_mode==='invoice'?'invoice':'quote'; const inputRows=array(state?.floors).reduce((n,f:any)=>n+array(f.rooms).reduce((m,r:any)=>m+array(r.items).length,0),0); const next=prepareSmartDocument(state,mode); const normalizedRows=array(next.floors).reduce((n,f:any)=>n+array(f.rooms).reduce((m,r:any)=>m+array(r.items).length,0),0); const visibleRows=visibleItems(next).filter(({item})=>Number(item.qty)>0).length; if(__DEV__)console.log('[QQIVA SMART]',{source:object(next.new_document).last_process_status||'MANUAL',documentType:mode,inputRows,normalizedRows,visibleRows,nextRoute}); const entry=await saveDocument(next); setState(entry.state); router.replace(nextRoute); } catch(e:any){Alert.alert('Không thể chuyển dữ liệu sang trình chỉnh sửa',e.message||String(e));} finally{setBusy(false);} };
  const save = async () => { try { setBusy(true); const mode=state?.document_mode==='invoice'?'invoice':'quote'; const entry=await saveDocument(prepareSmartDocument(state,mode)); setState(entry.state); Alert.alert('Đã lưu', `${entry.meta.document_no || 'Chứng từ'} đã được lưu vào SQLite.`); return entry; } catch(e:any){Alert.alert('Không lưu được',e.message||String(e)); return null;} finally{setBusy(false);} };

  if(!state)return <Screen title="Chứng từ thông minh"><Card><Text>Đang mở dữ liệu offline…</Text></Card></Screen>;

  return <Screen title="Chứng từ thông minh" subtitle="Nguồn → Chuẩn hóa → Hạng mục → Thông tin → Xem trước" right={<IconButton icon="close" onPress={()=>router.back()}/>}>
    <View style={s.stageBar}>{STAGES.map(x=><TouchableOpacity key={x.key} style={[s.stage,stage===x.key&&s.stageActive]} onPress={()=>void go(x.key)}><View style={[s.stageNo,stage===x.key&&s.stageNoActive]}><Text style={[s.stageNoT,stage===x.key&&{color:'#fff'}]}>{x.no}</Text></View><Text style={[s.stageText,stage===x.key&&s.stageTextActive]}>{x.label}</Text></TouchableOpacity>)}</View>
    <Chips value={state.document_mode} onChange={async v=>{const next={...state,document_mode:v==='invoice'?'invoice':'quote'};await commit(next)}} options={[{value:'quote',label:'Báo giá thông minh'},{value:'invoice',label:'Hóa đơn thông minh'}]}/>

    {stage==='source'?<>
      <Card><Text style={s.heroBadge}>{state.document_mode==='invoice'?'HÓA ĐƠN THÔNG MINH':'BÁO GIÁ THÔNG MINH'}</Text><Text style={s.heroTitle}>{state.document_mode==='invoice'?'ẢNH BẢNG ĐO → HÓA ĐƠN':'BẢN VẼ / 3D → BÁO GIÁ'}</Text><Muted>ChatGPT đọc ảnh/tệp nguồn. QQIVA không tự OCR; QQIVA nhận JSON trả về, kiểm tra cấu trúc và tự tính lại phép đo.</Muted></Card>
      <Card><SectionTitle>Bước 1 • {state.document_mode==='invoice'?'Sao chép Prompt Hóa đơn':'Sao chép Prompt Báo giá'}</SectionTitle><Muted>Prompt khóa cấu trúc Tầng → Phòng/Khu vực → Hạng mục → Phép đo, giữ phép tính gốc và cấm tự đoán dữ liệu không chắc chắn.</Muted><AppButton title="Sao chép Prompt" icon="content-copy" onPress={()=>void copyPrompt()}/></Card>
      <Card><SectionTitle>Bước 2 • Mở ChatGPT + gửi {state.document_mode==='invoice'?'ảnh bảng đo':'bản vẽ / ảnh 3D'}</SectionTitle><Muted>Dán Prompt vừa sao chép, đính kèm ảnh/tệp nguồn trong ChatGPT rồi gửi. Không cần API key trong QQIVA.</Muted><AppButton title="Mở ChatGPT" icon="open-in-new" onPress={()=>void openChatGPT()}/></Card>
      <Card><SectionTitle>Bước 3 • Dán kết quả từ ChatGPT vào QQIVA</SectionTitle><Muted>Chấp nhận JSON thuần, khối ```json ... ``` hoặc câu trả lời có JSON kèm giải thích.</Muted><Field label="Kết quả ChatGPT" multiline value={paste} onChangeText={v=>{setPaste(v);setImportStatus(v.trim()?'Đã có nội dung. Bấm “Kiểm tra & nạp kết quả”.':'Chưa dán kết quả.');void setPastedJson(v)}} placeholder="Dán JSON floors → rooms → items tại đây…"/><Row><AppButton compact variant="secondary" title="Dán từ bộ nhớ tạm" icon="clipboard-text" onPress={()=>void pasteClipboard()}/><AppButton compact variant="secondary" title="Xóa nội dung" icon="close" onPress={()=>void clearPaste()}/></Row><AppButton title={busy?'Đang kiểm tra…':'Kiểm tra & nạp kết quả'} disabled={busy} icon="check-decagram" onPress={()=>void importPaste()}/><Text style={importStatus.startsWith('⚠')?s.statusError:s.status}>{importStatus}</Text></Card>
      <Card><SectionTitle>Nguồn thay thế / đối chiếu</SectionTitle><Muted>Ảnh/PDF dưới đây chỉ được lưu trong máy để đối chiếu; QQIVA không tự đọc nội dung của chúng.</Muted><View style={s.sourceGrid}><SourceButton icon="camera" title="Chụp ảnh" onPress={()=>void sourceCamera()}/><SourceButton icon="image-multiple" title="Chọn ảnh" onPress={()=>void sourceImages()}/><SourceButton icon="file-pdf-box" title="PDF / bản vẽ" onPress={()=>void sourceDocs()}/><SourceButton icon="code-json" title="Nạp JSON" onPress={()=>void sourceJson()}/><SourceButton icon="ruler-square" title="Từ Đo trực tiếp" onPress={()=>void fromDirect()}/><SourceButton icon="pencil-plus" title="Nhập thủ công" onPress={()=>void addManual()}/></View><Field label="Mô tả / phạm vi cần làm" multiline value={object(state.new_document).scope_note||''} onChangeText={v=>{setState({...state,new_document:{...object(state.new_document),scope_note:v}});void setScopeNote(v)}}/></Card>
      <SectionTitle right={<AppButton compact variant="danger" title="Xóa nguồn" icon="delete-sweep" onPress={()=>confirm('Xóa nguồn','Xóa danh sách nguồn và các tệp nguồn đã lưu trong máy?',()=>void clearSources(true).then(refreshSources))}/>}>Nguồn đã lưu ({sources.length})</SectionTitle>
      {sources.length?sources.map((x,i)=><Card key={x.id}><Row>{x.kind==='IMAGE'?<ImageThumb path={x.path||x.url} size={60}/>:<View style={s.fileIcon}><MaterialCommunityIcons name={x.kind==='PDF'?'file-pdf-box':x.kind==='JSON'?'code-json':'file-outline'} size={30} color={colors.primary}/></View>}<View style={{flex:1}}><Text style={s.itemName}>{x.original_name||'Nguồn'}</Text><Muted>{x.kind||'FILE'} • {Math.max(1,Math.round(Number(x.size||0)/1024))} KB</Muted></View><IconButton icon="arrow-up" color={i?colors.primary:colors.textSoft} onPress={()=>void moveSource(x.id,-1).then(refreshSources)}/><IconButton icon="arrow-down" color={i<sources.length-1?colors.primary:colors.textSoft} onPress={()=>void moveSource(x.id,1).then(refreshSources)}/><IconButton icon="trash-can-outline" color={colors.danger} onPress={()=>void deleteSource(x.id).then(refreshSources)}/></Row></Card>):<Card><Muted>Chưa có tệp nguồn. Bạn vẫn có thể dán JSON hoặc nhập thủ công.</Muted></Card>}
      <AppButton title="Xem Bước 2 • Chuẩn hóa" icon="arrow-right" disabled={!stats.items} onPress={()=>void go('process')}/>
    </>:null}

    {stage==='process'?<>
      <Card><SectionTitle>Kiểm tra dữ liệu đã chuẩn hóa</SectionTitle><View style={s.statGrid}><Stat label="Nguồn" value={sources.length}/><Stat label="Tầng/Khu" value={stats.floors}/><Stat label="Phòng/Khu" value={stats.rooms}/><Stat label="Hạng mục" value={stats.items}/><Stat label="Cần kiểm tra" value={stats.checks} warn={!!stats.checks}/><Stat label="Thiếu ảnh" value={stats.noImage}/><Stat label="Thiếu giá" value={stats.noPrice}/><Stat label="LOCK" value={stats.locks}/></View>{stats.items?<Muted>Dữ liệu đã được chuẩn hóa cục bộ. Các dòng NEED_CHECK vẫn được giữ nguyên để người dùng xác nhận, không tự biến thành số chắc chắn.</Muted>:<Muted>Chưa có dữ liệu hạng mục. Quay lại Nguồn để nạp JSON, lấy từ Đo trực tiếp hoặc nhập thủ công.</Muted>}</Card>
      <Row><AppButton variant="secondary" title="← Nguồn" icon="arrow-left" onPress={()=>void go('source')}/><AppButton title="Hạng mục →" icon="arrow-right" onPress={()=>void go('items')}/></Row>
    </>:null}

    {stage==='items'?<>
      <SectionTitle right={<Row><AppButton compact variant="secondary" title="Thư viện" icon="package-variant" onPress={()=>setPicker(true)}/><AppButton compact variant="secondary" title="Thêm dòng" icon="plus" onPress={()=>void addManual()}/></Row>}>Hạng mục ({rows.length})</SectionTitle>
      {rows.map(({floor,room,item}:any)=><Card key={item.id}><Row><ImageThumb path={item.image} size={64}/><View style={{flex:1}}><Text style={s.itemName}>{item.name}</Text><Muted>{floor} › {room} • {item.status||''} • {item.confidence||''}</Muted></View><IconButton icon="trash-can-outline" color={colors.danger} onPress={()=>void removeItem(item.id)}/></Row><Field label="Tên hạng mục" value={item.name||''} onChangeText={v=>void patchItem(item.id,{name:v})}/><Row><View style={{flex:1}}><Field label="KL" keyboardType="decimal-pad" value={item.qty} onChangeText={v=>void patchItem(item.id,{qty:Number(v.replace(',','.')||0),status:'LOCKED'})}/></View><View style={{flex:1}}><Field label="ĐVT" value={item.unit||''} onChangeText={v=>void patchItem(item.id,{unit:v})}/></View><View style={{flex:1}}><Field label="Đơn giá" keyboardType="numeric" value={item.unit_price??item.price??0} onChangeText={v=>void patchItem(item.id,{unit_price:Number(v.replace(/\D/g,'')||0),price:Number(v.replace(/\D/g,'')||0)})}/></View></Row>{item.formula?<Field label="Công thức nguồn" value={item.formula} onChangeText={v=>void patchItem(item.id,{formula:v})}/>:null}<Field label="Mô tả / ghi chú" multiline value={[item.description,item.note].filter(Boolean).join('\n')} onChangeText={v=>void patchItem(item.id,{description:v})}/><Row><AppButton compact variant="secondary" title="Ảnh" icon="image-edit-outline" onPress={()=>void pickImages({ownerType:'DOCUMENT_ITEM',ownerId:item.id,multiple:false}).then(a=>a[0]&&patchItem(item.id,{image:a[0].uri}))}/>{String(item.status).includes('CHECK')?<AppButton compact variant="success" title="Đã kiểm tra" icon="check" onPress={()=>void patchItem(item.id,{status:'LOCKED',confidence:'CONFIRMED'})}/>:null}</Row></Card>)}
      {!rows.length?<Card><Muted>Chưa có hạng mục.</Muted></Card>:null}
      <Row><AppButton variant="secondary" title="← Chuẩn hóa" icon="arrow-left" onPress={()=>void go('process')}/><AppButton title="Thông tin →" icon="arrow-right" onPress={()=>void go('details')}/></Row>
    </>:null}

    {stage==='details'?<>
      <Card><SectionTitle>Khách hàng / công trình</SectionTitle><Field label="Khách hàng" value={p.customer||''} onChangeText={v=>void setProject({customer:v})}/><Field label="Địa chỉ / công trình" value={p.address||p.project_name||''} onChangeText={v=>void setProject({address:v,project_name:v})}/><Row><View style={{flex:1}}><Field label="Mã khách" value={p.customer_code||''} onChangeText={v=>void setProject({customer_code:v})}/></View><View style={{flex:1}}><Field label="Mã công trình" value={p.project_code||''} onChangeText={v=>void setProject({project_code:v})}/></View></Row><Row><View style={{flex:1}}><Field label="Số chứng từ" value={p.quote_no||''} onChangeText={v=>void setProject({quote_no:v})}/></View><View style={{flex:1}}><Field label="Ngày" value={p.quote_date||today()} onChangeText={v=>void setProject({quote_date:v})}/></View></Row><Field label="Ghi chú chứng từ" multiline value={p.quote_note||''} onChangeText={v=>void setProject({quote_note:v})}/></Card>
      <Card><SectionTitle>Giá trị</SectionTitle><ToggleRow label="Chiết khấu" value={!!p.pricing?.discount_enabled} onChange={v=>void setPricing({discount_enabled:v})}/>{p.pricing?.discount_enabled?<Row><View style={{flex:1}}><Chips value={p.pricing.discount_type||'percent'} onChange={v=>void setPricing({discount_type:v})} options={[{value:'percent',label:'%'},{value:'fixed',label:'Số tiền'}]}/></View><View style={{flex:1}}><Field label="Giá trị" keyboardType="numeric" value={p.pricing.discount_value||0} onChangeText={v=>void setPricing({discount_value:Number(v||0)})}/></View></Row>:null}<ToggleRow label="Phụ phí" value={!!p.pricing?.surcharge_enabled} onChange={v=>void setPricing({surcharge_enabled:v})}/>{p.pricing?.surcharge_enabled?<Row><View style={{flex:1}}><Field label="Tên phụ phí" value={p.pricing.surcharge_label||'Phụ phí'} onChangeText={v=>void setPricing({surcharge_label:v})}/></View><View style={{flex:1}}><Field label="Giá trị" keyboardType="numeric" value={p.pricing.surcharge_value||0} onChangeText={v=>void setPricing({surcharge_value:Number(v||0)})}/></View></Row>:null}<ToggleRow label="VAT" value={!!p.pricing?.vat_enabled} onChange={v=>void setPricing({vat_enabled:v})}/>{p.pricing?.vat_enabled?<Field label="VAT (%)" keyboardType="numeric" value={p.pricing.vat_rate||10} onChangeText={v=>void setPricing({vat_rate:Number(v||0)})}/>:null}</Card>
      <Card><SectionTitle>Tổng tiền</SectionTitle><Sum k="Tạm tính" v={totals.subtotal}/><Sum k="Chiết khấu" v={-totals.discount}/><Sum k="Phụ phí" v={totals.surcharge}/><Sum k="VAT" v={totals.vat}/><Divider/><Sum k="THÀNH TIỀN" v={totals.grand_total} strong/></Card>
      <Row><AppButton variant="secondary" title="← Hạng mục" icon="arrow-left" onPress={()=>void go('items')}/><AppButton title="Xem trước →" icon="arrow-right" onPress={()=>void go('preview')}/></Row>
    </>:null}

    {stage==='preview'?<>
      <Card><SectionTitle>Sẵn sàng tạo chứng từ</SectionTitle><Row><MaterialCommunityIcons name={state.document_mode==='invoice'?'receipt-text-check':'file-document-check'} size={42} color={colors.success}/><View style={{flex:1}}><Text style={s.previewTitle}>{state.document_mode==='invoice'?'HÓA ĐƠN':'BÁO GIÁ'} • {p.quote_no||'Chưa có số'}</Text><Muted>{p.customer||'Khách lẻ'} • {p.address||p.project_name||'Chưa có công trình'}</Muted><Text style={s.previewMoney}>{money(totals.grand_total)}</Text></View></Row><Divider/><Muted>{rows.length} hạng mục • {sources.length} nguồn • {stats.checks} dòng còn NEED_CHECK</Muted>{stats.checks?<Text style={s.warning}>Có dòng NEED_CHECK. QQIVA vẫn cho xem trước nhưng nên quay lại Hạng mục để xác nhận.</Text>:null}</Card>
      <AppButton title="Tiếp tục trong trình soạn" icon="pencil-ruler" disabled={busy} onPress={()=>void handoff('/document-editor')}/><AppButton variant="secondary" title="Lưu & mở xem trước" icon="file-eye-outline" disabled={busy} onPress={()=>void handoff('/document-preview')}/><Row><AppButton variant="secondary" title="← Thông tin" icon="arrow-left" onPress={()=>void go('details')}/><AppButton variant="secondary" title="Chỉ lưu" icon="content-save" disabled={busy} onPress={()=>void save()}/></Row>
    </>:null}

    <ProductPicker visible={picker} products={products} close={()=>setPicker(false)} pick={p=>void addProduct(p)}/>
  </Screen>;
}

function SourceButton({icon,title,onPress}:{icon:any;title:string;onPress:()=>void}){return <TouchableOpacity onPress={onPress} style={s.sourceButton}><MaterialCommunityIcons name={icon} size={26} color={colors.primary}/><Text style={s.sourceButtonText}>{title}</Text></TouchableOpacity>}
function Stat({label,value,warn=false}:{label:string;value:any;warn?:boolean}){return <View style={[s.stat,warn&&s.statWarn]}><Text style={s.statLabel}>{label}</Text><Text style={[s.statValue,warn&&{color:colors.danger}]}>{value}</Text></View>}
function Sum({k,v,strong=false}:{k:string;v:any;strong?:boolean}){return <Row><Text style={[s.sumK,strong&&s.strong]}>{k}</Text><Text style={[s.sumV,strong&&s.strong]}>{money(v)}</Text></Row>}
function ProductPicker({visible,products,close,pick}:{visible:boolean;products:any[];close:()=>void;pick:(p:any)=>void}){const [q,setQ]=useState('');const rows=products.filter(x=>!q||String(x.name).toLowerCase().includes(q.toLowerCase())).slice(0,100);return <Modal visible={visible} animationType="slide" onRequestClose={close}><Screen title="Chọn sản phẩm" right={<IconButton icon="close" onPress={close}/>}><Field label="Tìm kiếm" value={q} onChangeText={setQ}/>{rows.map(p=><TouchableOpacity key={p.id} onPress={()=>pick(p)}><Card><Row><ImageThumb path={p.image} size={52}/><View style={{flex:1}}><Text style={s.itemName}>{p.name}</Text><Muted>{p.unit||''} • {money(p.price)}</Muted></View><MaterialCommunityIcons name="plus-circle" size={24} color={colors.primary}/></Row></Card></TouchableOpacity>)}</Screen></Modal>}

const s=StyleSheet.create({heroBadge:{fontSize:12,fontWeight:'900',color:colors.primary},heroTitle:{fontSize:22,fontWeight:'900',color:colors.text,marginVertical:8},status:{fontSize:12,fontWeight:'800',color:colors.success},statusError:{fontSize:12,fontWeight:'800',color:colors.danger},stageBar:{flexDirection:'row',gap:5},stage:{flex:1,alignItems:'center',gap:4,paddingVertical:7,borderRadius:10,backgroundColor:colors.surface},stageActive:{backgroundColor:colors.surfaceSoft},stageNo:{width:24,height:24,borderRadius:12,backgroundColor:'#E0E6ED',alignItems:'center',justifyContent:'center'},stageNoActive:{backgroundColor:colors.primary},stageNoT:{fontSize:11,fontWeight:'900',color:colors.textSoft},stageText:{fontSize:9,fontWeight:'800',color:colors.textSoft,textAlign:'center'},stageTextActive:{color:colors.primary},sourceGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},sourceButton:{width:'31%',minHeight:88,borderWidth:1,borderColor:colors.border,borderRadius:14,alignItems:'center',justifyContent:'center',gap:7,backgroundColor:colors.surfaceSoft,padding:8},sourceButtonText:{fontWeight:'800',fontSize:11,color:colors.text,textAlign:'center'},fileIcon:{width:60,height:60,borderRadius:12,backgroundColor:colors.surfaceSoft,alignItems:'center',justifyContent:'center'},itemName:{fontWeight:'900',fontSize:14,color:colors.text},statGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},stat:{width:'31%',padding:10,borderRadius:12,backgroundColor:colors.surfaceSoft},statWarn:{backgroundColor:'#FFF0F1'},statLabel:{fontSize:10,color:colors.textSoft,fontWeight:'700'},statValue:{fontSize:18,color:colors.text,fontWeight:'900',marginTop:3},sumK:{flex:1,color:colors.textSoft},sumV:{fontWeight:'800',color:colors.text},strong:{fontWeight:'900',fontSize:16,color:colors.primary},previewTitle:{fontWeight:'900',fontSize:16,color:colors.text},previewMoney:{fontWeight:'900',fontSize:20,color:colors.primary,marginTop:6},warning:{fontSize:12,color:colors.danger,fontWeight:'800'}});
