import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

import { object, array, num, text } from '@/db/database';
import { getLiveState, saveLiveState } from '@/services/documentEngine';
import { evaluateFormula } from '@/services/formula';
import { getExportDirectory } from '@/services/media';
import { makeId, nowIso, today } from '@/services/id';

export async function getDirectMeasurement(){const state=await getLiveState();return normalize(object(state.direct_measurement));}
export async function saveDirectMeasurement(dm:any){const state=await getLiveState();state.direct_measurement=normalize(dm);await saveLiveState(state);return state.direct_measurement;}
export async function updateDirectMeta(patch:any){const dm=await getDirectMeasurement();dm.meta={...object(dm.meta),...patch};await saveDirectMeasurement(dm);return dm;}
export async function addFloor(name=''){const dm=await getDirectMeasurement();const floor={_direct_floor_uid:makeId('df'),name:name||`Tầng ${dm.floors.length+1}`,rooms:[]};dm.floors.push(floor);await saveDirectMeasurement(dm);return floor;}
export async function addRoom(floorId:string,name=''){const dm=await getDirectMeasurement();const floor=dm.floors.find((x:any)=>x._direct_floor_uid===floorId);if(!floor)throw new Error('Không tìm thấy tầng');const room={_direct_room_uid:makeId('dr'),name:name||`Phòng ${array(floor.rooms).length+1}`,items:[]};floor.rooms=array(floor.rooms);floor.rooms.push(room);await saveDirectMeasurement(dm);return room;}
export async function addMeasureItem(floorId:string,roomId:string,input:any={}){const dm=await getDirectMeasurement();const floor=dm.floors.find((x:any)=>x._direct_floor_uid===floorId);const room=array(floor?.rooms).find((x:any)=>x._direct_room_uid===roomId);if(!room)throw new Error('Không tìm thấy phòng');const formula=text(input.formula);const calc=formula?evaluateFormula(formula):null;const item={_direct_uid:makeId('di'),category:text(input.category||'phao'),confidence:'HIGH',description:text(input.description),formula,image:text(input.image),library_id:text(input.library_id),name:text(input.name),note:text(input.note),original_qty:calc??num(input.qty),price:num(input.price),qty:calc??num(input.qty),source:'DIRECT_MEASUREMENT',status:calc==null&&formula?'NEED_CHECK':'LOCK',unit:text(input.unit||'md'),measurements:array(input.measurements),created_at:nowIso()};room.items=array(room.items);room.items.push(item);await saveDirectMeasurement(dm);return item;}
export async function updateMeasureItem(itemId:string,patch:any){const dm=await getDirectMeasurement();for(const floor of dm.floors)for(const room of array(floor.rooms)){const item=array(room.items).find((x:any)=>x._direct_uid===itemId);if(item){Object.assign(item,patch);if(Object.prototype.hasOwnProperty.call(patch,'formula')){const calc=evaluateFormula(text(patch.formula));if(calc!=null){item.qty=calc;item.original_qty=calc;item.status='LOCK';}else item.status='NEED_CHECK';}await saveDirectMeasurement(dm);return item;}}throw new Error('Không tìm thấy phép đo');}
export async function deleteMeasureNode(kind:'floor'|'room'|'item',id:string){const dm=await getDirectMeasurement();if(kind==='floor')dm.floors=dm.floors.filter((x:any)=>x._direct_floor_uid!==id);else for(const floor of dm.floors){if(kind==='room')floor.rooms=array(floor.rooms).filter((x:any)=>x._direct_room_uid!==id);else for(const room of array(floor.rooms))room.items=array(room.items).filter((x:any)=>x._direct_uid!==id);}await saveDirectMeasurement(dm);}

export function measurementStats(dm:any){let floors=0,rooms=0,items=0,total=0;const units:Record<string,number>={};for(const f of array(dm?.floors)){floors++;for(const r of array(f.rooms)){rooms++;for(const i of array(r.items)){items++;const q=num(i.qty);total+=q;const u=text(i.unit||'');units[u]=(units[u]||0)+q;}}}return{floors,rooms,items,total,units};}

export async function applyDirectToDocument(kind:'quote'|'invoice'='invoice'){const state=await getLiveState();const dm=await getDirectMeasurement();state.document_mode=kind;state.floors=dm.floors.map((f:any,fi:number)=>({floor_order:fi+1,name:f.name,rooms:array(f.rooms).map((r:any)=>({name:r.name,items:array(r.items).map((i:any)=>({...i,source:'DIRECT_MEASUREMENT',calculated_qty:num(i.qty),original_qty:num(i.qty)}))}))}));state.project={...object(state.project),project_name:text(dm.meta?.project_name),address:text(dm.meta?.project_address||state.project?.address),quote_date:text(dm.meta?.measure_date||today())};await saveLiveState(state);return state;}

export async function confirmMeasurement(input:{signer_name:string;note?:string;signature?:string}){const dm=await getDirectMeasurement();dm.confirmation={status:'CONFIRMED',confirmed_at:nowIso(),signer_name:text(input.signer_name),note:text(input.note),signature:text(input.signature),snapshot:JSON.parse(JSON.stringify(dm.floors)),snapshot_hash:simpleHash(JSON.stringify(dm.floors))};await saveDirectMeasurement(dm);return dm.confirmation;}

export async function exportMeasurementJson(){const dm=await getDirectMeasurement();const dir=await getExportDirectory();const path=`${dir}QQIVA_BANG_DO_${Date.now()}.qqivameasure`;await FileSystem.writeAsStringAsync(path,JSON.stringify({schema_version:'qqiva.measure.v2',exported_at:nowIso(),direct_measurement:dm},null,2),{encoding:FileSystem.EncodingType.UTF8});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(path,{dialogTitle:'Xuất bảng đo QQIVA'});return path;}

export async function importMeasurementJson(uri:string,mode:'merge'|'update'|'replace'='merge'){const raw=await FileSystem.readAsStringAsync(uri,{encoding:FileSystem.EncodingType.UTF8});const payload=JSON.parse(raw);const incoming=normalize(payload.direct_measurement||payload);const current=await getDirectMeasurement();if(mode==='replace'){await saveDirectMeasurement(incoming);return incoming;}const byId=new Map<string,any>();for(const f of current.floors)for(const r of array(f.rooms))for(const i of array(r.items))if(i._direct_uid)byId.set(i._direct_uid,i);for(const f of incoming.floors){let tf=current.floors.find((x:any)=>x._direct_floor_uid&&x._direct_floor_uid===f._direct_floor_uid)||current.floors.find((x:any)=>x.name===f.name);if(!tf){current.floors.push(f);continue;}for(const r of array(f.rooms)){let tr=array(tf.rooms).find((x:any)=>x._direct_room_uid&&x._direct_room_uid===r._direct_room_uid)||array(tf.rooms).find((x:any)=>x.name===r.name);if(!tr){tf.rooms=array(tf.rooms);tf.rooms.push(r);continue;}for(const i of array(r.items)){const existing=i._direct_uid?byId.get(i._direct_uid):null;if(existing&&mode==='update')Object.assign(existing,i);else if(!existing){tr.items=array(tr.items);tr.items.push(i);}}}}await saveDirectMeasurement(current);return current;}

function normalize(v:any){const d=object(v);return{meta:{document_kind:'invoice',last_stage:'info',measure_date:today(),measured_by:'',output_mode:'DOCUMENT',project_name:'',project_address:'',...object(d.meta)},floors:array(d.floors),confirmation:{status:'UNCONFIRMED',confirmed_at:'',note:'',signature:'',signer_name:'',snapshot:null,snapshot_hash:'',...object(d.confirmation)}};}
function simpleHash(s:string){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return String(h>>>0);}
