import { getDatabase, num, text, upsertFinanceRow } from '@/db/database';
import { getJson, setJson } from '@/db/jsonStore';
import { currentMonth, makeId, nowIso, today } from '@/services/id';

type BookType='BUSINESS'|'PERSONAL'; type TxType='INCOME'|'EXPENSE';

export async function getFinance(bookType:BookType='BUSINESS',month=currentMonth()){
  const store=await getStore();const book=store.books[bookType];const active=(book.transactions||[]).filter((x:any)=>!x.deleted_at);const monthly=active.filter((x:any)=>String(x.date||'').slice(0,7)===month);const todayRows=active.filter((x:any)=>String(x.date||'').slice(0,10)===today());
  const income=(xs:any[])=>xs.filter(x=>x.transaction_type==='INCOME').reduce((s,x)=>s+num(x.amount),0);const expense=(xs:any[])=>xs.filter(x=>x.transaction_type==='EXPENSE').reduce((s,x)=>s+num(x.amount),0);const opening=(book.accounts||[]).filter((x:any)=>x.active!==false).reduce((s:number,x:any)=>s+num(x.opening_balance),0);
  return {schema_version:store.schema_version,book,summary:{month,period_income:income(monthly),period_expense:expense(monthly),period_net:income(monthly)-expense(monthly),today_income:income(todayRows),today_expense:expense(todayRows),balance:opening+income(active)-expense(active)}};
}

export async function saveTransaction(input:any){const bt=bookType(input.book_type),kind=txType(input.transaction_type),amount=num(input.amount);if(amount<=0)throw new Error('Số tiền phải lớn hơn 0');const date=text(input.date||today()).trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('Ngày giao dịch không hợp lệ');const store=await getStore();const book=store.books[bt];const cat=findActive(book.categories,input.category_id,kind);const acc=findActive(book.accounts,input.account_id);if(!cat)throw new Error('Hãy chọn danh mục');if(!acc)throw new Error('Hãy chọn tài khoản/quỹ');const now=nowIso();let row=(book.transactions||[]).find((x:any)=>x.id===input.id&&!x.deleted_at);const path=categoryPath(book,input.category_id,kind);if(!row){row={id:makeId('FIN'),created_at:now,created_by:'QQIVA_ANDROID_OFFLINE'};(book.transactions||=[]).push(row);}const partyName=text(input.party_name).trim().slice(0,180);Object.assign(row,{book_id:book.id,book_type:bt,business_id:book.business_id||'',owner_user_id:book.owner_user_id||'LOCAL-OWNER',transaction_type:kind,amount,currency:'VND',date,note:text(input.note).trim().slice(0,500),category_id:cat.id,category_name:cat.name,category_root_id:path[0]?.id||cat.id,category_path_ids:path.map((x:any)=>x.id),category_path_names:path.map((x:any)=>x.name),account_id:acc.id,account_name:acc.name,project_uid:text(input.project_uid).trim(),project_name:text(input.project_name).trim(),party_type:text(input.party_type).trim().toUpperCase(),party_name:partyName,source_type:text(input.source_type||'MANUAL').trim().toUpperCase(),source_id:text(input.source_id).trim(),updated_at:now,sync:{status:'LOCAL_ONLY',revision:num(row.sync?.revision)+1}});if(bt==='BUSINESS'&&partyName)upsertCustomerInBook(book,partyName,'TRANSACTION');book.updated_at=now;await saveStore(store);const db=await getDatabase();await upsertFinanceRow(db,bt,row);return row;}

export async function deleteTransaction(bookTypeInput:BookType,id:string){const store=await getStore();const book=store.books[bookTypeInput];const row=(book.transactions||[]).find((x:any)=>x.id===id&&!x.deleted_at);if(!row)throw new Error('Không tìm thấy giao dịch');row.deleted_at=nowIso();row.updated_at=row.deleted_at;row.sync={status:'LOCAL_ONLY',revision:num(row.sync?.revision)+1};await saveStore(store);const db=await getDatabase();await upsertFinanceRow(db,bookTypeInput,row);}

export async function saveCategory(input:any){const bt=bookType(input.book_type),kind=txType(input.type),name=text(input.name).trim();if(!name)throw new Error('Tên danh mục không được để trống');const store=await getStore(),book=store.books[bt];const id=text(input.id).trim();const parentId=text(input.parent_id).trim();if(parentId){const parent=(book.categories||[]).find((x:any)=>x.id===parentId&&x.active!==false&&x.type===kind);if(!parent)throw new Error('Danh mục cha không hợp lệ');if(id&&id===parentId)throw new Error('Danh mục không thể là cấp con của chính nó');if(id&&categoryPath(book,parentId,kind).some((x:any)=>x.id===id))throw new Error('Không thể tạo vòng lặp danh mục');}
  let row=id?(book.categories||[]).find((x:any)=>x.id===id):null;if(!row){const same=(book.categories||[]).filter((x:any)=>x.type===kind&&text(x.parent_id)===parentId);row={id:makeId('CAT'),type:kind,name,icon:text(input.icon||'•'),parent_id:parentId,active:true,sort_order:Math.max(0,...same.map((x:any)=>num(x.sort_order)))+10,system_default:false};(book.categories||=[]).push(row);}else Object.assign(row,{type:kind,name,icon:text(input.icon||row.icon||'•'),parent_id:Object.prototype.hasOwnProperty.call(input,'parent_id')?parentId:text(row.parent_id),active:true,...(input.sort_order!=null?{sort_order:num(input.sort_order)}:{})});row.updated_at=nowIso();book.updated_at=row.updated_at;await saveStore(store);return row;}

export async function reorderCategories(bt:BookType,kind:TxType,parentId:string,order:string[]){const store=await getStore(),book=store.books[bt];const map=new Map((book.categories||[]).filter((x:any)=>x.type===kind&&text(x.parent_id)===parentId).map((x:any)=>[x.id,x]));let pos=10;for(const id of order){const row:any=map.get(id);if(row){row.sort_order=pos;pos+=10;map.delete(id);}}for(const row of Array.from(map.values()) as any[]){row.sort_order=pos;pos+=10;}book.updated_at=nowIso();await saveStore(store);}

export async function deleteCategory(bt:BookType,id:string){const store=await getStore(),book=store.books[bt];const row=(book.categories||[]).find((x:any)=>x.id===id);if(!row)throw new Error('Không tìm thấy danh mục');const stack=[id],now=nowIso();while(stack.length){const cur=stack.pop()!;const target=(book.categories||[]).find((x:any)=>x.id===cur);if(!target)continue;target.active=false;target.updated_at=now;stack.push(...(book.categories||[]).filter((x:any)=>text(x.parent_id)===cur&&x.active!==false).map((x:any)=>x.id));}book.updated_at=now;await saveStore(store);}

export async function saveAccount(input:any){const bt=bookType(input.book_type),name=text(input.name).trim();if(!name)throw new Error('Tên tài khoản/quỹ không được để trống');const store=await getStore(),book=store.books[bt];let row=(book.accounts||[]).find((x:any)=>x.id===input.id);if(!row){row={id:makeId('ACC'),name,kind:text(input.kind||'OTHER').toUpperCase(),opening_balance:Math.max(0,num(input.opening_balance)),active:true,sort_order:((book.accounts||[]).length+1)*10,system_default:false};(book.accounts||=[]).push(row);}else Object.assign(row,{name,kind:text(input.kind||row.kind||'OTHER').toUpperCase(),opening_balance:Math.max(0,num(input.opening_balance??row.opening_balance)),active:true});book.updated_at=nowIso();await saveStore(store);return row;}
export async function deleteAccount(bt:BookType,id:string){const store=await getStore(),book=store.books[bt];const row=(book.accounts||[]).find((x:any)=>x.id===id);if(!row)throw new Error('Không tìm thấy tài khoản/quỹ');row.active=false;row.updated_at=nowIso();await saveStore(store);}

export async function saveBudget(input:any){const bt=bookType(input.book_type),month=text(input.month||currentMonth()).slice(0,7),categoryId=text(input.category_id).trim(),limit=num(input.limit);if(!/^\d{4}-\d{2}$/.test(month))throw new Error('Tháng ngân sách không hợp lệ');if(limit<0)throw new Error('Ngân sách không được âm');const store=await getStore(),book=store.books[bt],now=nowIso();let row=(book.budgets||[]).find((x:any)=>x.month===month&&text(x.category_id)===categoryId);if(!row){row={id:makeId('BUD'),month,category_id:categoryId,limit,created_at:now};(book.budgets||=[]).push(row);}else row.limit=limit;row.updated_at=now;row.sync={status:'LOCAL_ONLY',revision:num(row.sync?.revision)+1};await saveStore(store);return row;}

export async function saveFinanceCustomer(name:string){name=name.trim();if(!name)throw new Error('Tên khách hàng không được để trống');const store=await getStore(),book=store.books.BUSINESS;const row=upsertCustomerInBook(book,name,'MANUAL');book.updated_at=nowIso();await saveStore(store);return row;}
export async function deleteFinanceCustomer(id:string){const store=await getStore(),book=store.books.BUSINESS;const row=(book.customers||[]).find((x:any)=>x.id===id);if(!row)throw new Error('Không tìm thấy khách hàng');row.active=false;row.updated_at=nowIso();await saveStore(store);}

function upsertCustomerInBook(book:any,name:string,source:string){book.customers||=[];const key=name.toLocaleLowerCase('vi');let row=book.customers.find((x:any)=>text(x.name).toLocaleLowerCase('vi')===key);if(!row){row={id:makeId('FCUS'),name,active:true,source,created_at:nowIso()};book.customers.push(row);}else{row.active=true;row.name=name;}row.updated_at=nowIso();return row;}
function categoryPath(book:any,id:string,kind:TxType){const out:any[]=[];const map=new Map((book.categories||[]).filter((x:any)=>x.type===kind).map((x:any)=>[x.id,x]));let cur:any=map.get(id),guard=0;while(cur&&guard++<30){out.unshift(cur);cur=cur.parent_id?map.get(cur.parent_id):null;}return out;}
function findActive(rows:any[],id:any,type?:string){return (rows||[]).find(x=>x.id===id&&x.active!==false&&(!type||x.type===type));}
function bookType(v:any):BookType{return String(v).toUpperCase()==='PERSONAL'?'PERSONAL':'BUSINESS'};function txType(v:any):TxType{return String(v).toUpperCase()==='INCOME'?'INCOME':'EXPENSE'};
async function getStore(){return getJson<any>('finance_ledger',{schema_version:'finance-1',books:{BUSINESS:{id:'BOOK-BUSINESS-LOCAL',type:'BUSINESS',business_id:'LOCAL-BUSINESS',owner_user_id:'LOCAL-OWNER',currency:'VND',categories:[],accounts:[],budgets:[],transactions:[],customers:[]},PERSONAL:{id:'BOOK-PERSONAL-LOCAL',type:'PERSONAL',business_id:'',owner_user_id:'LOCAL-OWNER',currency:'VND',categories:[],accounts:[],budgets:[],transactions:[],customers:[]}}});}
async function saveStore(store:any){await setJson('finance_ledger',store);}
