import { array, num, object, text } from '@/db/database';
import { getLiveState, saveLiveState, allocateDocumentNo } from '@/services/documentEngine';
import { getProduct } from '@/services/products';
import { nowIso, today, makeId } from '@/services/id';

export async function getQuick(kind:'quote'|'invoice'){const s=await getLiveState();const flow=object(s.quick_flow);return flow[kind]||{created_at:nowIso(),stage:'info',info:{customer:'',address:'',phone:'',tax_id:'',title:'',note:''},items:[],customize:{template:'images',orientation:'auto',doc_no:'',doc_date:'',validity_days:30,pricing:{},payment_terms:{enabled:true}},quote_state:null};}
export async function saveQuick(kind:'quote'|'invoice',quick:any){const s=await getLiveState();s.quick_flow={...object(s.quick_flow),[kind]:quick};await saveLiveState(s);return quick;}
export async function addQuickProduct(kind:'quote'|'invoice',productId:string){const q=await getQuick(kind);const p=await getProduct(productId);if(!p)throw new Error('Không tìm thấy sản phẩm');q.items=array(q.items);q.items.push({id:makeId('QI'),library_id:p.id,name:p.name,image:p.image,unit:p.unit,price:num(p.price),qty:1,description:p.description,status:kind==='quote'?'QUICK_QUOTE':'QUICK_INVOICE'});await saveQuick(kind,q);return q;}
export async function addQuickManual(kind:'quote'|'invoice',input:any){const q=await getQuick(kind);q.items=array(q.items);q.items.push({id:makeId('QI'),name:text(input.name||'Hạng mục'),image:text(input.image),unit:text(input.unit||'cái'),price:num(input.price),qty:num(input.qty||1),description:text(input.description),status:kind==='quote'?'QUICK_QUOTE':'QUICK_INVOICE'});await saveQuick(kind,q);return q;}
export async function updateQuickItem(kind:'quote'|'invoice',id:string,patch:any){const q=await getQuick(kind);const item=array(q.items).find((x:any)=>x.id===id);if(item)Object.assign(item,patch);await saveQuick(kind,q);return q;}
export async function removeQuickItem(kind:'quote'|'invoice',id:string){const q=await getQuick(kind);q.items=array(q.items).filter((x:any)=>x.id!==id);await saveQuick(kind,q);return q;}
export async function applyQuickToDocument(kind:'quote'|'invoice'){const q=await getQuick(kind);const s=await getLiveState();const p=object(s.project);p.customer=text(q.info?.customer);p.address=text(q.info?.address);p.project_name=p.address;p.quote_note=text(q.info?.note);p.quote_no=text(q.customize?.doc_no)||await allocateDocumentNo(kind);p.quote_date=text(q.customize?.doc_date)||today();p.validity_days=num(q.customize?.validity_days||30);p.pricing={...object(p.pricing),...object(q.customize?.pricing)};p.payment_terms={...object(p.payment_terms),...object(q.customize?.payment_terms)};s.project=p;s.document_mode=kind;s.quote_mode='QUICK';s.floors=[{floor_order:1,name:kind==='quote'?'BÁO GIÁ NHANH':'HÓA ĐƠN NHANH',rooms:[{name:text(q.info?.title||'Sản phẩm'),items:array(q.items).map((x:any)=>({...x,qty:num(x.qty),price:num(x.price),unit_price:num(x.price),price_multiplier:1}))}]}];if(kind==='quote')s.quick_quote={items:q.items,quote_state:null};else s.quick_invoice={items:q.items,quote_state:null};await saveLiveState(s);return s;}
