import { getDatabase, num, text } from '@/db/database';
import { makeId, nowIso } from '@/services/id';

const BUSINESS='LOCAL-BUSINESS',BRANCH='LOCAL-BRANCH',WAREHOUSE='LOCAL-WAREHOUSE',DEVICE='ANDROID-DEVICE';const MICROS=1_000_000;

export async function foundationStatus(){const db=await getDatabase();const [b,br,w,d,profiles,skus]=await Promise.all([db.getFirstAsync<any>('SELECT * FROM retail_business WHERE business_id=?',BUSINESS),db.getFirstAsync<any>('SELECT * FROM retail_branch WHERE branch_id=?',BRANCH),db.getFirstAsync<any>('SELECT * FROM retail_warehouse WHERE warehouse_id=?',WAREHOUSE),db.getFirstAsync<any>('SELECT * FROM retail_device WHERE device_id=?',DEVICE),db.getFirstAsync<{n:number}>('SELECT COUNT(*) n FROM retail_product_profile WHERE business_id=?',BUSINESS),db.getFirstAsync<{n:number}>('SELECT COUNT(*) n FROM retail_sku WHERE business_id=?',BUSINESS)]);return{ok:!!(b&&br&&w&&d),schema_version:'qqiva.retail.v1',business:b,branch:br,warehouse:w,device:d,counts:{products:profiles?.n||0,skus:skus?.n||0}};}

export async function reconcileRetail(){const db=await getDatabase();const profiles=await db.getAllAsync<any>('SELECT product_id FROM retail_product_profile WHERE business_id=?',BUSINESS);for(const p of profiles){const lib=await db.getFirstAsync<any>('SELECT id,name,group_id FROM products WHERE id=?',p.product_id);await db.runAsync('UPDATE retail_product_profile SET library_missing=?,product_name_snapshot=?,library_group_id_snapshot=?,updated_at_utc=? WHERE business_id=? AND product_id=?',lib?0:1,lib?.name||'',lib?.group_id||'',nowIso(),BUSINESS,p.product_id);}return foundationStatus();}

export async function listRetailCatalog(search=''){const db=await getDatabase();const q=`%${search.trim()}%`;const products=search.trim()?await db.getAllAsync<any>('SELECT * FROM products WHERE hidden=0 AND (name LIKE ? OR catalog_key LIKE ?) ORDER BY name',q,q):await db.getAllAsync<any>('SELECT * FROM products WHERE hidden=0 ORDER BY name');const out:any[]=[];for(const p of products){const profile=await db.getFirstAsync<any>('SELECT * FROM retail_product_profile WHERE business_id=? AND product_id=?',BUSINESS,p.id);const skus=await db.getAllAsync<any>('SELECT * FROM retail_sku WHERE business_id=? AND product_id=? ORDER BY sku_code',BUSINESS,p.id);for(const sku of skus){sku.barcodes=await db.getAllAsync<any>('SELECT * FROM retail_barcode WHERE sku_id=? AND active=1 ORDER BY is_primary DESC',sku.sku_id);sku.balance=await db.getFirstAsync<any>('SELECT * FROM stock_balance WHERE business_id=? AND warehouse_id=? AND sku_id=?',BUSINESS,WAREHOUSE,sku.sku_id);}out.push({...p,retail:profile,skus});}return{ok:true,items:out};}

export async function enableProductForRetail(input:any){const db=await getDatabase();const productId=text(input.product_id).trim();const product=await db.getFirstAsync<any>('SELECT * FROM products WHERE id=?',productId);if(!product)throw new Error('Không tìm thấy sản phẩm trong thư viện');const now=nowIso();await db.runAsync(`INSERT OR REPLACE INTO retail_product_profile (business_id,product_id,product_name_snapshot,library_group_id_snapshot,track_stock,active,library_missing,created_at_utc,updated_at_utc) VALUES (?,?,?,?,?,?,?,?,?)`,BUSINESS,productId,product.name,product.group_id||'',input.track_stock===false?0:1,1,0,now,now);
  let sku=await db.getFirstAsync<any>('SELECT * FROM retail_sku WHERE business_id=? AND product_id=? LIMIT 1',BUSINESS,productId);if(!sku){const skuId=makeId('SKU');const code=text(input.sku_code).trim()||`SKU-${productId.slice(-8).toUpperCase()}`;await db.runAsync(`INSERT INTO retail_sku (sku_id,business_id,product_id,sku_code,variant_name,unit,cost_price_minor,retail_price_minor,currency,track_stock,allow_negative_stock,min_stock_micros,active,created_at_utc,updated_at_utc) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,skuId,BUSINESS,productId,code,text(input.variant_name),text(input.unit||product.unit),input.cost_price_minor==null?null:Math.round(num(input.cost_price_minor)),Math.round(num(input.retail_price_minor??product.price)), 'VND',input.track_stock===false?0:1,input.allow_negative_stock?1:0,Math.round(num(input.min_stock_micros)),1,now,now);sku=await db.getFirstAsync<any>('SELECT * FROM retail_sku WHERE sku_id=?',skuId);}return{ok:true,profile:await db.getFirstAsync<any>('SELECT * FROM retail_product_profile WHERE business_id=? AND product_id=?',BUSINESS,productId),sku};}

export async function saveSku(input:any){const db=await getDatabase();const skuId=text(input.sku_id).trim()||makeId('SKU');const productId=text(input.product_id).trim();const product=await db.getFirstAsync<any>('SELECT * FROM products WHERE id=?',productId);if(!product)throw new Error('Không tìm thấy sản phẩm');await enableProductForRetail({product_id:productId,unit:input.unit||product.unit});const old=await db.getFirstAsync<any>('SELECT * FROM retail_sku WHERE sku_id=?',skuId);const now=nowIso();const code=text(input.sku_code||old?.sku_code).trim();if(!code)throw new Error('Mã SKU không được để trống');await db.runAsync(`INSERT OR REPLACE INTO retail_sku (sku_id,business_id,product_id,sku_code,variant_name,unit,cost_price_minor,retail_price_minor,currency,track_stock,allow_negative_stock,min_stock_micros,active,created_at_utc,updated_at_utc) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,skuId,BUSINESS,productId,code,text(input.variant_name??old?.variant_name),text(input.unit??old?.unit??product.unit),input.cost_price_minor==null?old?.cost_price_minor??null:Math.round(num(input.cost_price_minor)),input.retail_price_minor==null?old?.retail_price_minor??Math.round(num(product.price)):Math.round(num(input.retail_price_minor)),'VND',input.track_stock===false?0:1,input.allow_negative_stock?1:0,Math.round(num(input.min_stock_micros??old?.min_stock_micros)),input.active===false?0:1,old?.created_at_utc||now,now);return db.getFirstAsync<any>('SELECT * FROM retail_sku WHERE sku_id=?',skuId);}

export async function saveBarcode(input:any){const db=await getDatabase();const skuId=text(input.sku_id).trim(),barcode=text(input.barcode).trim();if(!skuId||!barcode)throw new Error('Thiếu SKU hoặc mã vạch');const sku=await db.getFirstAsync<any>('SELECT * FROM retail_sku WHERE sku_id=?',skuId);if(!sku)throw new Error('Không tìm thấy SKU');const old=await db.getFirstAsync<any>('SELECT * FROM retail_barcode WHERE business_id=? AND barcode=?',BUSINESS,barcode);if(old&&old.sku_id!==skuId)throw new Error('Mã vạch đã gắn với SKU khác');if(input.is_primary)await db.runAsync('UPDATE retail_barcode SET is_primary=0 WHERE sku_id=?',skuId);const id=text(input.barcode_id).trim()||old?.barcode_id||makeId('BAR');await db.runAsync(`INSERT OR REPLACE INTO retail_barcode (barcode_id,business_id,sku_id,barcode,barcode_type,is_primary,active,created_at_utc) VALUES (?,?,?,?,?,?,?,?)`,id,BUSINESS,skuId,barcode,text(input.barcode_type||'EAN').toUpperCase(),input.is_primary?1:0,input.active===false?0:1,old?.created_at_utc||nowIso());return db.getFirstAsync<any>('SELECT * FROM retail_barcode WHERE barcode_id=?',id);}

export async function findSkuByBarcode(barcode:string){const db=await getDatabase();return db.getFirstAsync<any>(`SELECT s.*,p.name product_name,p.image,p.price library_price,b.barcode FROM retail_barcode b JOIN retail_sku s ON s.sku_id=b.sku_id JOIN products p ON p.id=s.product_id WHERE b.business_id=? AND b.barcode=? AND b.active=1 AND s.active=1`,BUSINESS,barcode.trim());}

export async function listStockBalances(){const db=await getDatabase();return db.getAllAsync<any>(`SELECT s.*,p.name product_name,p.image,COALESCE(b.on_hand_micros,0) on_hand_micros,COALESCE(b.on_hand_micros,0)/1000000.0 qty FROM retail_sku s JOIN products p ON p.id=s.product_id LEFT JOIN stock_balance b ON b.business_id=s.business_id AND b.warehouse_id=? AND b.sku_id=s.sku_id WHERE s.business_id=? AND s.active=1 ORDER BY p.name,s.sku_code`,WAREHOUSE,BUSINESS);}
export async function listStockTransactions(limit=100,skuId=''){const db=await getDatabase();return skuId?db.getAllAsync<any>(`SELECT t.*,s.sku_code,p.name product_name FROM stock_transaction t JOIN retail_sku s ON s.sku_id=t.sku_id JOIN products p ON p.id=s.product_id WHERE t.business_id=? AND t.sku_id=? ORDER BY occurred_at_utc DESC LIMIT ?`,BUSINESS,skuId,limit):db.getAllAsync<any>(`SELECT t.*,s.sku_code,p.name product_name FROM stock_transaction t JOIN retail_sku s ON s.sku_id=t.sku_id JOIN products p ON p.id=s.product_id WHERE t.business_id=? ORDER BY occurred_at_utc DESC LIMIT ?`,BUSINESS,limit);}

export async function postStockMovement(input:any){const db=await getDatabase();const skuId=text(input.sku_id).trim();const sku=await db.getFirstAsync<any>('SELECT * FROM retail_sku WHERE sku_id=? AND business_id=?',skuId,BUSINESS);if(!sku)throw new Error('Không tìm thấy SKU');const qty=Math.abs(num(input.qty??input.quantity));if(qty<=0)throw new Error('Số lượng phải lớn hơn 0');const type=text(input.tx_type||'IN').toUpperCase();const positive=['OPENING','PURCHASE','CUSTOMER_RETURN','ADJUST_IN','IN'].includes(type);const deltaMicros=Math.round(qty*MICROS)*(positive?1:-1);const balance=await db.getFirstAsync<any>('SELECT on_hand_micros FROM stock_balance WHERE business_id=? AND warehouse_id=? AND sku_id=?',BUSINESS,WAREHOUSE,skuId);const next=num(balance?.on_hand_micros)+deltaMicros;if(next<0&&!sku.allow_negative_stock)throw new Error('Tồn kho không đủ và SKU không cho phép tồn âm');const now=nowIso();const txId=makeId('STX'),refId=text(input.reference_id)||makeId('REF'),idem=text(input.idempotency_key)||makeId('IDEM');await db.withTransactionAsync(async()=>{await db.runAsync(`INSERT INTO stock_transaction (stock_tx_id,business_id,warehouse_id,sku_id,tx_type,qty_delta_micros,unit_cost_minor,reference_type,reference_id,reversal_of_stock_tx_id,idempotency_key,actor_id,device_id,occurred_at_utc,created_at_utc,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,txId,BUSINESS,WAREHOUSE,skuId,type,deltaMicros,input.unit_cost_minor==null?null:Math.round(num(input.unit_cost_minor)),text(input.reference_type||'MANUAL'),refId,text(input.reversal_of_stock_tx_id),idem,'QQIVA_ANDROID',DEVICE,text(input.occurred_at_utc||now),now,text(input.note));await db.runAsync(`INSERT INTO stock_balance (business_id,warehouse_id,sku_id,on_hand_micros,updated_at_utc,ledger_version) VALUES (?,?,?,?,?,1) ON CONFLICT(business_id,warehouse_id,sku_id) DO UPDATE SET on_hand_micros=excluded.on_hand_micros,updated_at_utc=excluded.updated_at_utc,ledger_version=stock_balance.ledger_version+1`,BUSINESS,WAREHOUSE,skuId,next,now);});return{ok:true,stock_tx_id:txId,on_hand_micros:next,qty:next/MICROS};}

export async function stockIntegrity(){const db=await getDatabase();const ledgers=await db.getAllAsync<any>('SELECT sku_id,SUM(qty_delta_micros) total FROM stock_transaction WHERE business_id=? AND warehouse_id=? GROUP BY sku_id',BUSINESS,WAREHOUSE);const errors:Array<{sku_id:string;ledger:number;balance:number}>=[];for(const x of ledgers){const b=await db.getFirstAsync<any>('SELECT on_hand_micros FROM stock_balance WHERE business_id=? AND warehouse_id=? AND sku_id=?',BUSINESS,WAREHOUSE,x.sku_id);if(num(b?.on_hand_micros)!==num(x.total))errors.push({sku_id:x.sku_id,ledger:num(x.total),balance:num(b?.on_hand_micros)});}return{ok:errors.length===0,errors};}

export type CartLine={sku_id:string;qty:number;unit_price?:number;discount?:number;tax_rate?:number;note?:string};
export async function completeSale(input:{items:CartLine[];customer_name?:string;payment_method?:string;paid_amount?:number;external_ref?:string;discount_total?:number;tax_total?:number}){if(!input.items?.length)throw new Error('Giỏ hàng đang trống');const db=await getDatabase();const resolved:Array<{sku:any;qty:number;price:number;discount:number;tax:number;total:number;note:string}>=[];let subtotal=0;for(const [idx,line] of input.items.entries()){const sku=await db.getFirstAsync<any>(`SELECT s.*,p.name product_name FROM retail_sku s JOIN products p ON p.id=s.product_id WHERE s.sku_id=? AND s.business_id=? AND s.active=1`,line.sku_id,BUSINESS);if(!sku)throw new Error(`SKU dòng ${idx+1} không hợp lệ`);const qty=Math.max(0,num(line.qty));if(qty<=0)throw new Error(`Số lượng dòng ${idx+1} phải lớn hơn 0`);const price=Math.max(0,Math.round(num(line.unit_price??sku.retail_price_minor)));const lineSubtotal=Math.round(price*qty);const discount=Math.max(0,Math.round(num(line.discount)));const tax=Math.max(0,Math.round((lineSubtotal-discount)*num(line.tax_rate)/100));const total=Math.max(0,lineSubtotal-discount+tax);subtotal+=lineSubtotal;resolved.push({sku,qty,price,discount,tax,total,note:text(line.note)});}const discountTotal=Math.max(0,Math.round(num(input.discount_total)))+resolved.reduce((s,x)=>s+x.discount,0);const taxTotal=Math.max(0,Math.round(num(input.tax_total)))+resolved.reduce((s,x)=>s+x.tax,0);const total=Math.max(0,subtotal-discountTotal+taxTotal);const paid=Math.max(0,Math.round(num(input.paid_amount??total)));const now=nowIso();const saleId=makeId('SALE'),saleNo=`SALE-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`,idem=makeId('IDEM');
  await db.withTransactionAsync(async()=>{for(const x of resolved){if(x.sku.track_stock){const bal=await db.getFirstAsync<any>('SELECT on_hand_micros FROM stock_balance WHERE business_id=? AND warehouse_id=? AND sku_id=?',BUSINESS,WAREHOUSE,x.sku.sku_id);const needed=Math.round(x.qty*MICROS);if(num(bal?.on_hand_micros)<needed&&!x.sku.allow_negative_stock)throw new Error(`Không đủ tồn kho: ${x.sku.product_name}`);}}
    await db.runAsync(`INSERT INTO sale (sale_id,business_id,branch_id,warehouse_id,device_id,sale_no,customer_id,customer_name,status,currency,subtotal_minor,discount_total_minor,tax_total_minor,total_minor,paid_total_minor,payment_status,idempotency_key,created_by_actor_id,created_at_utc,completed_at_utc) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,saleId,BUSINESS,BRANCH,WAREHOUSE,DEVICE,saleNo,'',text(input.customer_name),'COMPLETED','VND',subtotal,discountTotal,taxTotal,total,paid,paid>=total?'PAID':paid>0?'PARTIAL':'UNPAID',idem,'QQIVA_ANDROID',now,now);
    for(const [idx,x] of resolved.entries()){const itemId=makeId('SLI');await db.runAsync(`INSERT INTO sale_item (sale_item_id,sale_id,line_no,product_id,sku_id,product_name_snapshot,sku_code_snapshot,variant_name_snapshot,unit_snapshot,qty_micros,unit_price_minor,discount_minor,tax_minor,line_total_minor,unit_cost_snapshot_minor,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,itemId,saleId,idx+1,x.sku.product_id,x.sku.sku_id,x.sku.product_name,x.sku.sku_code,x.sku.variant_name||'',x.sku.unit||'',Math.round(x.qty*MICROS),x.price,x.discount,x.tax,x.total,x.sku.cost_price_minor??null,x.note);if(x.sku.track_stock){const bal=await db.getFirstAsync<any>('SELECT on_hand_micros FROM stock_balance WHERE business_id=? AND warehouse_id=? AND sku_id=?',BUSINESS,WAREHOUSE,x.sku.sku_id);const next=num(bal?.on_hand_micros)-Math.round(x.qty*MICROS);await db.runAsync(`INSERT INTO stock_transaction (stock_tx_id,business_id,warehouse_id,sku_id,tx_type,qty_delta_micros,unit_cost_minor,reference_type,reference_id,reversal_of_stock_tx_id,idempotency_key,actor_id,device_id,occurred_at_utc,created_at_utc,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,makeId('STX'),BUSINESS,WAREHOUSE,x.sku.sku_id,'SALE',-Math.round(x.qty*MICROS),x.sku.cost_price_minor??null,'SALE',saleId,'',makeId('IDEM'),'QQIVA_ANDROID',DEVICE,now,now,'Xuất bán POS');await db.runAsync(`INSERT INTO stock_balance (business_id,warehouse_id,sku_id,on_hand_micros,updated_at_utc,ledger_version) VALUES (?,?,?,?,?,1) ON CONFLICT(business_id,warehouse_id,sku_id) DO UPDATE SET on_hand_micros=excluded.on_hand_micros,updated_at_utc=excluded.updated_at_utc,ledger_version=stock_balance.ledger_version+1`,BUSINESS,WAREHOUSE,x.sku.sku_id,next,now);}}
    if(paid>0)await db.runAsync(`INSERT INTO sale_payment (payment_id,sale_id,business_id,method,amount_minor,status,external_ref,idempotency_key,paid_at_utc,created_at_utc) VALUES (?,?,?,?,?,?,?,?,?,?)`,makeId('SPAY'),saleId,BUSINESS,text(input.payment_method||'CASH'),paid,'CONFIRMED',text(input.external_ref),makeId('IDEM'),now,now);
  });return getSale(saleId);}

export async function listSales(limit=100){const db=await getDatabase();return db.getAllAsync<any>('SELECT * FROM sale WHERE business_id=? ORDER BY created_at_utc DESC LIMIT ?',BUSINESS,limit);}
export async function getSale(saleId:string){const db=await getDatabase();const sale=await db.getFirstAsync<any>('SELECT * FROM sale WHERE sale_id=?',saleId);if(!sale)return null;const items=await db.getAllAsync<any>('SELECT * FROM sale_item WHERE sale_id=? ORDER BY line_no',saleId);const payments=await db.getAllAsync<any>('SELECT * FROM sale_payment WHERE sale_id=? ORDER BY paid_at_utc',saleId);return{ok:true,sale,items,payments};}
